instill-ai/protobufs

CODEOWNERS
To start a rigorous code review process, we adopt GitHub's [CODEOWNERS](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) logic. 
---
Please make sure the PR commits
- follow the [7 rules of commit messages](https://chris.beams.io/posts/git-commit/)
- follow the [conventional commits guidelines](https://www.conventionalcommits.org/)
- are rearrange to squash trivial commits together (use [git rebase](http://gitready.com/advanced/2009/03/20/reorder-commits-with-rebase.html))
=> ci: add code owners

pipeline/pipeline.proto
Because
- we  some definitions that are not used
This commit
- remove unused code
=> fix(pipeline): remove unsed code

buf.gen.yaml, model/README.md, pipeline/README.md
Because
- we need a doc for our gRPC definition
This commit
- add README.md for the gRPC inside service folder
- add configuration for gRPC doc generation
- close #10
=> docs: add README.md inside service folders and configuration of gRPC doc generation

model/README.md, model/model.swagger.json, pipeline/README.md, pipeline/pipeline.swagger.json
Because
- change `model-backend` proto file
- change `pipeline-backend` proto file
This commit
- modify OpenAPI spec and README.md for `pipeline-backend` and `model-backend`
=> chore(doc): modify OpenAPI spec and README.md

instill/model/v1alpha/model.proto
Because
- Each field should have an annotation following by [this](https://github.com/googleapis/googleapis/blob/master/google/api/field_behavior.proto)
This commit
- Add annotations for message fields
=> chore(model): add field annotation

instill/mgmt/v1alpha/mgmt.proto, instill/mgmt/v1alpha/mgmt.swagger.json
Because
- we want to manage users in an independent backend `mgmt-backend`.
This commit
- add proto file
- add generated OpenAPI YAML file
=> feat: add mgmt-backend proto

instill/pipeline/v1alpha/pipeline.proto, instill/pipeline/v1alpha/pipeline_service.proto
Because
- best practices are adopted following the path of Google AIP-122
This commit
- is a work for the pipeline package aligning with PR #63
=> refactor(pipeline): adopt Google AIP-122

instill/model/v1alpha/model.proto, instill/model/v1alpha/model_service.proto
Because
- support creating a model using stream gRPC
This commit
- add creating a model with stream gRPC method
=> chore(model): add create a model with stream gRPC

vdp/model/v1alpha/model.proto
Because
- Support Keypoint task
This commit
- Keypoint detection model output
=> chore: add keypoint detection model output

vdp/model/v1alpha/model.proto
Because
- Missing comment for message keypoint 
This commit
- Add missing comment
=> chore: update comment for keypoint message

vdp/model/v1alpha/classification_output_definition.proto, vdp/model/v1alpha/detection_output_definition.proto, vdp/model/v1alpha/keypoint_output_definition.proto, vdp/model/v1alpha/model.proto, vdp/model/v1alpha/unspecify_output_definition.proto
Because
- fixed warning and error in model backend
This commit
- remove unused import and add comment to inference output
=> chore(model): remove unused import and add comment to inference output

vdp/model/v1alpha/common.proto, vdp/model/v1alpha/detection_output.proto, vdp/model/v1alpha/model.proto, vdp/model/v1alpha/ocr_output.proto
Because
- support OCR task
This commit
- add OCR task output format
=> feat(model): add ocr output

vdp/model/v1alpha/model.proto
Because
- support OCR task
This commit
- add OCR task in model instance
=> chore: add ocr instance task

vdp/model/v1alpha/boundingbox_output.proto
Because
- buf lint failed due to a missing comment
This commit
- add the missing comment
=> chore(model): add missing comment for task_field

vdp/pipeline/v1alpha/pipeline.proto
Because
- support instance segmentation task
This commit
- add instance segmentation task
=> chore(pipeline): support instance segmentation task

vdp/model/v1alpha/model.proto, vdp/model/v1alpha/task_text_to_image.proto
Because
- support text-to-image task
This commit
- add text to image output standardized format
=> chore: add text to image output task

openapiv2/openapiv2.swagger.yaml, vdp/model/v1alpha/model.proto, vdp/model/v1alpha/task_text_to_image.proto
Because
- support text to image task
This commit
- add text to image to model instance task
=> chore(model): add text to image in model instance task

openapiv2/openapiv2.swagger.yaml, vdp/model/v1alpha/task_text_to_image.proto
Because
- missing comment for fields and failed but lint
This commit
- add missing comment
=> chore(model): add comment

openapiv2/openapiv2.swagger.yaml, vdp/pipeline/v1alpha/pipeline.proto
Because
- pipeline package shows import error 
This commit
- fix the missing model task package
- update openapi yaml
=> chore(pipeline): fix import pacakge 

openapiv2/openapiv2.swagger.yaml, vdp/mgmt/v1alpha/mgmt.proto
Because
- we want to link a user with the billing service
This commit
- add billing ID in the `user` message
=> chore(mgmt): add billing id field in user message

vdp/model/v1alpha/model.proto, vdp/model/v1alpha/task_classification.proto, vdp/model/v1alpha/task_detection.proto, vdp/model/v1alpha/task_instance_segmentation.proto, vdp/model/v1alpha/task_keypoint.proto, vdp/model/v1alpha/task_ocr.proto, vdp/model/v1alpha/task_semantic_segmentation.proto
Because
- the stream method support multiple tasks
This commit
- define task input for stream method
=> chore: update task input for stream method

openapiv2/openapiv2.swagger.yaml, vdp/connector/v1alpha/connector.proto, vdp/connector/v1alpha/connector_public_service.proto
Because
- This commit is not adopted in the implementation.
This commit
- reverts commit dd5d72d9fa4ce05cf06b65f2036bf3e1fa80c955
=> chore(connector): Revert commit dd5d72d9fa4ce05cf06b65f2036bf3e1fa80c955

base/mgmt/v1alpha/metric.proto, base/mgmt/v1alpha/mgmt_public_service.proto, openapiv2/openapiv2.swagger.yaml
Because
- update `ListPipelineTriggerRecords` to plural
This commit
- update `ListPipelineTriggerRecords` to plural
=> chore(mgmt): update `ListPipelineTriggerRecords` to plural

openapiv2/openapiv2.swagger.yaml, vdp/connector/v1alpha/connector.proto, vdp/pipeline/v1alpha/pipeline.proto
Because
- we are going to support audio-to-text task
This commit
- support audio DataPayload in connector and pipeline
=> chore(pipeline,connector): support audio datapayload

base/usage/v1alpha/usage.proto, openapiv2/openapiv2.swagger.yaml
Because
- update collected model definition id to uid
This commit
- update collected model definition id to uid
=> chore(usage): update model definition id to uid

openapiv2/openapiv2.swagger.yaml, vdp/pipeline/v1alpha/common.proto, vdp/pipeline/v1alpha/pipeline.proto
Because
- we are going to support pipeline sharing feature
This commit
- add pipeline permission setting
=> chore(pipeline): add pipeline permission setting

common/healthcheck/v1beta/healthcheck.proto, core/metric/v1beta/metric.proto, core/metric/v1beta/metric_service.proto, core/mgmt/v1beta/metric.proto, core/mgmt/v1beta/mgmt.proto, core/mgmt/v1beta/mgmt_private_service.proto, core/mgmt/v1beta/mgmt_public_service.proto, core/usage/v1beta/usage.proto, core/usage/v1beta/usage_service.proto, model/controller/v1alpha/controller.proto, model/model/v1alpha/model.proto, openapiv2/openapiv2.swagger.yaml, vdp/controller/v1beta/controller.proto, vdp/controller/v1beta/controller_service.proto, vdp/pipeline/v1beta/common.proto, vdp/pipeline/v1beta/connector.proto, vdp/pipeline/v1beta/connector_definition.proto, vdp/pipeline/v1beta/operator_definition.proto, vdp/pipeline/v1beta/pipeline.proto, vdp/pipeline/v1beta/pipeline_private_service.proto, vdp/pipeline/v1beta/pipeline_public_service.proto
Because
- we are going to release beta version of Core and VDP
This commit
- upgrade Core and VDP version to v1beta
=> chore(core,vdp): upgrade version to v1beta

core/mgmt/v1beta/mgmt.proto, core/mgmt/v1beta/mgmt_private_service.proto, core/mgmt/v1beta/mgmt_public_service.proto, openapiv2/openapiv2.swagger.yaml
Because
- we need subscription endpoints to return the user and organization subscription plan and quota informations
This commit
- add subscription endpoints
=> chore(mgmt): add subscription endpoints

core/mgmt/v1beta/mgmt.proto, openapiv2/openapiv2.swagger.yaml
Because
- we need to show more details for subscription quota
This commit
- add quota of private pipeline and trigger in Subscription endpoint
=> chore(mgmt): add quota of private pipeline and trigger in Subscription endpoint

common/openapi/v1beta/options.proto, core/mgmt/v1beta/mgmt.proto, core/mgmt/v1beta/mgmt_private_service.proto, core/mgmt/v1beta/mgmt_public_service.proto, core/usage/v1beta/usage_service.proto, model/controller/v1alpha/controller_service.proto, model/model/v1alpha/model_private_service.proto, model/model/v1alpha/model_public_service.proto, openapiv2/internal/openapiv2.swagger.yaml, openapiv2/openapiv2.swagger.yaml, vdp/controller/v1beta/controller_service.proto, vdp/pipeline/v1beta/connector.proto, vdp/pipeline/v1beta/connector_definition.proto, vdp/pipeline/v1beta/operator_definition.proto, vdp/pipeline/v1beta/pipeline.proto, vdp/pipeline/v1beta/pipeline_private_service.proto, vdp/pipeline/v1beta/pipeline_public_service.proto
Because
- we are going to simplify the pricing plan, we no longer need the quota limitation.
This commit
- remove quota limitation from subscription API
=> chore(core): remove quota limitation

model/model/v1alpha/model.proto, model/model/v1alpha/model_public_service.proto, openapiv2/model/service.swagger.yaml
Because
- Support listing model versions for a particular model namepsace
This commit
- add ListModelVersions method
- update version related paths
=> chore(model): add list model versions and update version path

core/mgmt/v1beta/mgmt.proto, openapiv2/core/service.swagger.yaml
Because
- We're going to provide a new pricing plan TEAM PRO.
This commit
- Adds new TEAM_PRO subscription plan.
=> feat(mgmt): add new TEAM_PRO subscription plan

model/model/v1alpha/model.proto, openapiv2/model/service.swagger.yaml
Because
- Model page needs to support displaying custom profile image
This commit
- add model profile image in model message
=> chore(model): add model profile image

model/model/v1alpha/model.proto
Because
- Region should be immutable
This commit
- make region immutable
- add missing optional keyword
=> chore(model): make region immutable and add missing optional keyword

artifact/artifact/v1alpha/artifact.proto, artifact/artifact/v1alpha/artifact_public_service.proto, openapiv2/artifact/service.swagger.yaml
Because
we need to provide the knowledge base api
This commit
define the knowledge base rpc and message
=> feat(artifact): add kb related rpc & message

artifact/artifact/v1alpha/artifact.proto, artifact/artifact/v1alpha/artifact_public_service.proto, openapiv2/artifact/service.swagger.yaml
Because 
of consistency with other services
This commit 
follows the convention
Note:
this PR is only for POC, and there are some known issues will be refactored soon.
=> feat(knowledge-base): follow the convention

artifact/artifact/v1alpha/artifact.proto, artifact/artifact/v1alpha/artifact_public_service.proto, openapiv2/artifact/service.swagger.yaml
Because
wee need to upload files for knowledge base 
This commit
define the related api spec
=> feat(kb): file-related api spec

artifact/artifact/v1alpha/artifact.proto, artifact/artifact/v1alpha/artifact_public_service.proto, model/model/v1alpha/model.proto, openapiv2/model/service.swagger.yaml
Because
- We are going to introduce `tags` system for model.
This commit
- Adds `tags` field in model.
=> feat(model): add `tags` field in model

core/mgmt/v1beta/mgmt.proto, vdp/pipeline/v1beta/pipeline.proto
Reverts instill-ai/protobufs#368
=> chore(mgmt): revert "make ApiToken `last_use_time` optional"

artifact/artifact/v1alpha/artifact.proto, artifact/artifact/v1alpha/artifact_public_service.proto, openapiv2/artifact/service.swagger.yaml
Because
knowledge base api need to support namespace
This commit
add owner paramter
=> chore(kb): refactor kb endpoints

artifact/artifact/v1alpha/artifact.proto, artifact/artifact/v1alpha/artifact_private_service.proto, model/model/v1alpha/model.proto, model/model/v1alpha/model_public_service.proto, openapiv2/artifact/service.swagger.yaml, openapiv2/model/service.swagger.yaml
Because
- We are going to support model version deletion
This commit
- add repository tag deletion in artifact-backend contract
- add model version deletion in model-backend contract
=> feat(model): support model version deletion

artifact/artifact/v1alpha/artifact.proto, openapiv2/artifact/service.swagger.yaml
Because
file list needs # of chunks and tokens
This commit
add this two fields
=> feat(kb): add some file metadata

core/mgmt/v1beta/mgmt.proto, openapiv2/core/service.swagger.yaml
Because
- We want to offer a free pricing plan for organizations.
This commit
- Adds support for organizations with a free plan.
=> chore(mgmt): add free plan for organization

model/model/v1alpha/model_public_service.proto, openapiv2/model/service.swagger.yaml
Because
- update http path for list endpoints
This commit
- update http path for list endpoints
=> chore(model): update http path for list endpoints

artifact/artifact/v1alpha/artifact.proto, artifact/artifact/v1alpha/artifact_public_service.proto, artifact/artifact/v1alpha/chunk.proto, openapiv2/artifact/service.swagger.yaml
Because
we need to rename kb to catalog
This commit
rename the kb to catalog
=> feat(kb): change kb to catalog

artifact/artifact/v1alpha/artifact.proto, artifact/artifact/v1alpha/artifact_public_service.proto, artifact/artifact/v1alpha/file_catalog.proto, artifact/artifact/v1alpha/qa.proto, openapiv2/artifact/service.swagger.yaml
Because
1. catelog need to support more file upload 
2. question answering api
3. file catalog api
This commit
add related proto
=> feat(catalog): more file type, qa api, and file catalog api

artifact/artifact/v1alpha/file_catalog.proto, openapiv2/artifact/service.swagger.yaml
Because
file catalog api needs to return the original data
This commit
add the original_filed in proto
=> feat(catalog): add original data field

model/model/v1alpha/model.proto, model/model/v1alpha/model_public_service.proto, openapiv2/model/service.swagger.yaml
Because
- we need model run logging endpoints for trigger records
This commit
- added model run logging endpoints
todos:
=> feat(model): added model run logging endpoints

artifact/artifact/v1alpha/artifact_public_service.proto, artifact/artifact/v1alpha/conversation.proto, openapiv2/artifact/service.swagger.yaml
Because
catalog needs to support conversation and message resource
This commit
adds the related api
=> feat(catalog): add conversation and message api

artifact/artifact/v1alpha/artifact.proto, artifact/artifact/v1alpha/artifact_public_service.proto, artifact/artifact/v1alpha/chunk.proto, artifact/artifact/v1alpha/conversation.proto, openapiv2/artifact/service.swagger.yaml
Because
there are some typo
This commit
fix the typo
=> fix(catalog): fix some typo

artifact/artifact/v1alpha/artifact_public_service.proto, artifact/artifact/v1alpha/conversation.proto, model/model/v1alpha/model.proto, openapiv2/model/service.swagger.yaml, openapiv2/vdp/service.swagger.yaml, vdp/pipeline/v1beta/pipeline_public_service.proto
Because
- When only "Scaling" is displayed, users don't know which specific status it refers to.
This commit
- add separate states for scaling
=> feat(model): add separate states for scaling

artifact/artifact/v1alpha/artifact_public_service.proto, openapiv2/artifact/service.swagger.yaml
Because
making endpoint concise is needed
This commit
refactored the endpoint
=> feat(catalog): change get file catalog endpoint

model/model/v1alpha/model.proto, openapiv2/model/service.swagger.yaml, openapiv2/vdp/service.swagger.yaml, vdp/pipeline/v1beta/pipeline.proto
* fix input & output type
Because
- component run should return input/output raw data
This commit
- add fields
=> feat(run): component run logging query filter

artifact/artifact/v1alpha/file_catalog.proto, openapiv2/artifact/service.swagger.yaml
Because
there is a extra unnecessary filed
This commit
removed the filed
=> fix(artifact): remove transform content uid

app/app/v1alpha/app.proto, openapiv2/app/service.swagger.yaml
Because
need more fields for app update
This commit
add necessary fileds
=> feat(app): add necessary filed for app api

app/app/v1alpha/app_public_service.proto, openapiv2/app/service.swagger.yaml
Because
- fix wrong chat endpoint path
This commit
- update chat endpoint path
=> chore(app): update chat endpoint path

app/app/v1alpha/app.proto, app/app/v1alpha/app_public_service.proto, openapiv2/app/service.swagger.yaml
Because
we no need the `UpdateAIAssistantAppPlayground `
This commit
removes it
=> chore(app): remove no need api

artifact/artifact/v1alpha/object.proto, openapiv2/artifact/service.swagger.yaml
Because
old fileds in object message is not clear
This commit
makes some fields in object clear
=> feat(blob): improve fields name

core/mgmt/v1beta/metric.proto, core/mgmt/v1beta/mgmt_public_service.proto
Reverts instill-ai/protobufs#507
=> feat(metric): revert "model trigger table records api"

app/app/v1alpha/agent.proto, app/app/v1alpha/app.proto, app/app/v1alpha/conversation.proto, artifact/artifact/v1alpha/artifact.proto, core/mgmt/v1beta/mgmt_public_service.proto, openapi/v2/service.swagger.yaml
Because
agent will use a lot of artifact and app funciton.
This commit
try to reuse the old catalog api and ai assistant api.
=> feat(artifact&app): design agent related api

app/app/v1alpha/app_public_service.proto, app/app/v1alpha/conversation.proto, openapi/v2/service.swagger.yaml
Because
we need the new endpoint for chat.
This commit
add the related apis
=> feat(agent): add chat and chat message apis

app/app/v1alpha/agent.proto, app/app/v1alpha/app_public_service.proto, app/app/v1alpha/conversation.proto, openapi/v2/service.swagger.yaml
Because
we are going to remove the app-related api
This commit
adds api for agent
=> feat(agent): add agent contract

app/app/v1alpha/conversation.proto, openapi/v2/service.swagger.yaml
Because
agent's message has citation
This commit
add citation type for web search tool
=> feat(agent): add citations message

app/app/v1alpha/agent.proto, openapi/v2/service.swagger.yaml
Because
lacks the dispaly name in agent aupdate request 
This commit
1. add display name in update agent request
2. changes comments
=> fix(agent): add display name

model/model/v1alpha/model.proto, openapi/v2/service.swagger.yaml
Because
- unify hardware prop type
This commit
- update model hardware prop type
=> chore(model): update model hardware prop type

.spectral.yaml, app/app/v1alpha/app_public_service.proto, app/app/v1alpha/table.proto, openapi/v2/conf.proto, openapi/v2/service.swagger.yaml
Because
- Introducing the new Table services.  
- OpenAPI generator is encountering rate-limit issues in the local development environment.  
This Commit
- Implements table endpoints.  
- Removes OpenAPI pre-commit hooks.
=> feat(agent): implement table endpoints

artifact/artifact/v1alpha/artifact.proto, artifact/artifact/v1alpha/chunk.proto
Because
- support metadata filter for chunks
This commit
- support metadata filter for chunks
=> chore(artifact): support metadata filter for chunks

agent/agent/v1alpha/table.proto, openapi/v2/service.swagger.yaml
This commit
- adjusts data type of NumberCell
=> chore(table): adjust data type of NumberCell

agent/agent/v1alpha/chat.proto, openapi/v2/service.swagger.yaml
Because
- add citation number
This commit
- add citation number
=> chore(agent): add citation number

agent/agent/v1alpha/chat.proto, openapi/v2/service.swagger.yaml
Because
- rename url citation to web
This commit
- rename url citation to web
=> chore(agent): rename url citation to web

agent/agent/v1alpha/chat.proto, openapi/v2/service.swagger.yaml
Because
- update citation
This commit
- update citation
=> chore(agent): update citation

agent/agent/v1alpha/chat.proto, agent/agent/v1alpha/table.proto, openapi/v2/service.swagger.yaml
This commit
- adjusts file cell and citation format
=> chore(table): adjust file cell and citation format

agent/agent/v1alpha/chat.proto
Because
- add event messages
This commit
- add event messages
=> chore(chat): add event messages

agent/agent/v1alpha/chat.proto, agent/agent/v1alpha/table.proto, openapi/v2/service.swagger.yaml
This commit
- adds enable_web_search config
=> chore(agent): add enable_web_search config

.github/CONTRIBUTING.md, README.md, artifact/artifact/v1alpha/artifact.proto, core/mgmt/v1beta/mgmt.proto, core/mgmt/v1beta/mgmt_public_service.proto, core/usage/v1beta/usage.proto, model/model/v1alpha/model.proto, model/model/v1alpha/model_definition.proto, openapi/v2/conf.proto, openapi/v2/service.swagger.yaml, pipeline/pipeline/v1beta/common.proto, pipeline/pipeline/v1beta/pipeline.proto, pipeline/pipeline/v1beta/pipeline_public_service.proto, pipeline/pipeline/v1beta/secret.proto
This commit
- updates domain name
=> chore(all): update domain name

agent/agent/v1alpha/agent_public_service.proto, agent/agent/v1alpha/chat.proto, agent/agent/v1alpha/table.proto, openapi/v2/service.swagger.yaml
Because
- We are introducing a special agent that specializes in table building,
This commit
- Adds endpoints for the table builder agent.
- Removes unused endpoints.
=> chore(table): add endpoints for table builder agent

agent/agent/v1alpha/table.proto, openapi/v2/service.swagger.yaml
Because
- we want to allow users to configure the detailed format of numbers,
this commit
- adds number format options.
=> chore(table): add number format options

agent/agent/v1alpha/chat.proto, openapi/v2/service.swagger.yaml
This commit
- updates helper endpoint for listing context options for chat
=> chore(table): update helper endpoint for listing context options for chat

agent/agent/v1alpha/common.proto, openapi/v2/service.swagger.yaml
This commit
- simplifies chat context message with a flatten structure.
=> chore(agent): simplify chat context message
