instill-ai/protobufs

- pipeline/pipeline.proto
Because 
- we want to make the specs more concise
This commit
-  fix(pipeline-backend): change the definition of protobuff
1. add liveness and readiness
2. add rpc for uploading file to inference
3. refactor timestamp
4. refactor message for update request
-  refactor: change the spec of recipe and list pipeline
1. rename `DataSource` to `Source`
2. rename `DataDestination` to `Destinaion`
3. rename `VisualDataOperator` to `Model`
4. add `Scheduler` into `Source`
5. add `Name`
6. add `View` and its enum instead of `with_recipe`
- fix(pipeline): change `model_name` to `name`
> fix(pipeline-backend): change the definition of protobuff

- .github/semantic.yml
- .github/workflows/add-issue-to-prj.yml
- .github/workflows/add-pr-to-prj.yml
Because
- we'd like to track issues and PRs in the [VDP](https://github.com/orgs/instill-ai/projects/5) project.
- we want to check whether the PR is semantic
This commit
- add Github Actions to add issues and PRs to the VDP project according to [automating the project (beta)](https://docs.github.com/en/issues/trying-out-the-new-projects-experience/managing-the-visibility-of-your-projects)
- add `semantic.yml` for Semantic Pull Requests
> ci: add issue and pr to VDP project

- model/model.swagger.json
- pipeline/pipeline.swagger.json
Because
- we decide to put the OpenAPI specs inside the `pipeline` or `model`
This commit
- add temporary OpenAPI specs
- close #9
> docs(docs): add temporary OpenAPI specs

- model/model.proto
Because
- As a user, I need model backend support gRPC to manage my vision AI models
This commit
- Add protobuf definition for model-backend which contain methods:
1. Liveness and Readiness
2. CreateModelByUpload (used for gRPC stream upload): upload the model file into Triton server but do not load it into the server yet
3. LoadModel: load model into Triton server
4. UnloadModel: unload model from Triton server
5. PredictModelByUpload (used for gRPC stream): inference model with an input image
6. ListModels: list all models
7. GetModel: get model information by name
> feat(model-backend): add protobuf for model-backend service

- pipeline/pipeline.proto
Because
- the convention is snake_case in the field name, we should follow the convention
This commit
- use `full_name` instead of `fullName`
> fix(pipeline): use `full_name` instead of `fullName`

- README.md
Because
- enrich more content to README.md to tell users what this repository is
This commit
- add description in README.md
- close #11
> docs(doc): add description in README.md

- model/model.proto
Because
- Field definitions in the .proto files must use lower_case_underscore_separated_names. These names will be mapped to the native naming convention in generated code for each programming language.
This commit
- Update all fields with the above format
- Remove unsued messages
- close #21
> refactor(model): reformat fields name

- model/model.proto
Because
- there is an endpoint for inference with URL or base64 
This commit
- update the REST endpoint and message request
> fix(model): predict method for url/base64

- model/model.proto
Because
- Model name and version is not allowed to update
This commit
- Move model name and version out of updated model info message struct
> fix(model): move name and version out of updated model info message struct

- pipeline/pipeline.proto
Because
- new `model-backend`  supports URL/base64 inference endpoint, so `pipeline-backend` can also have the trigger endpoint to trigger pipeline and send URL/base64 to `model-backend`
- separate image and URL/base64 trigger request
This commit
- create TriggerPipeline rpc for new model-backend
> fix: create TriggerPipeline rpc for new model-backend

- instill/model/v1alpha/model.proto
- instill/pipeline/v1alpha/pipeline.proto
Because
- we are tinkering with the interface for adopting the new protobufs for `pipeline-backend` and `model-backend`
This commit
- simplify the output JSON structure
- introduce update patch message
> refactor: simplify output and update patch

- instill/model/v1alpha/model.proto
Because
- `CreateModel` method is currently unuseful since model-backend deals with only binary file upload for creating a model
This commit
- Remove `CreateModel`
> chore(model): remove unused CreateModel method

- buf.gen.yaml
- instill/model/v1alpha/model.swagger.json
- instill/pipeline/v1alpha/pipeline.swagger.json
Because
- response output standard follows snake_case to disambiguate REST and gRPC naming convention
This commit
- configure `openapiv2` plugin with `json_names_for_fields=false` based on the [official guideline](https://grpc-ecosystem.github.io/grpc-gateway/docs/development/grpc-gateway_v2_migration_guide/#we-now-use-the-camelcase-json-names-by-default)
> fix: fix openapi using snake case

- instill/model/v1alpha/model.proto
Because
- It is convenient for users when creating a model from their GitHub repository
This commit
- Add a method to create a model by GitHub URL
> feat(model): add method create model by GitHub

- instill/model/v1alpha/model.proto
Because
- Model version have GitHub information including repository, branch, tag and commit hash
This commit
- Move GitHub from Model message to ModelVersion message
> fix(model): move github from model to model version

- instill/connector/v1alpha/connector.proto
Because
- connector-backend is introduced as a microservice for managing all source and destination data connectors
This commit
- initiate the connector protobuf
> feat(connector): add protobuf

- instill/model/v1alpha/model.proto
Because
- It is convenient to make inferences with multiple files
This commit
- Support making inference with multiple files by adding length of files in the request
> fix(model): support inferencing multiple files 

- instill/connector/v1alpha/connector.proto
- instill/model/v1alpha/definition.proto
- instill/model/v1alpha/model.proto
- instill/model/v1alpha/model_service.swagger.json
Because
A model and a model instance from the same model definition may require different fields. Use the model definition `GitHub` as an example, to create a model, a repository is required. But for each imported model instance, an extra `tag` field is needed. Therefore, for each supported model definition, we provide specifications for both model and model instance.
This commit
- remove `public` and `custom` fields from `ModelDefinition` message
- remove `Spec` message and add `model_spec` and `model_instance_spec` in `ModelDefinition` message
> chore(model): add `model_spec` and `model_instance_spec` in `ModelDefinition`

- instill/model/v1alpha/model.proto
- instill/model/v1alpha/model_service.proto
Because
-  Support publish and unpublish a model
This commit
- Add publish and unpublish method
> chore(model): add publish/unpublish methods

- instill/model/v1alpha/model.proto
- instill/model/v1alpha/model_definition.proto
- instill/model/v1alpha/model_service.swagger.json
Because
- in GET operation, it is desirable to return results that the user is interested in 
This commit
- make `view` parameter optional
- add `view` parameter to `GET /model-definitions/*`
- add `view` parameter to `GET /models/*`
- add `view` parameter to `GET /models/*/instances/*`
- add `view` parameter to `lookUp` custom methods
> fix(model): add optional view param for GET operation

- instill/connector/v1alpha/connector_definition.proto
- instill/model/v1alpha/model.proto
- openapiv2/openapiv2.swagger.yaml
Because
- We can safely use string to replace `google.protobuf.Struct` for now, as `google.protobuf.FieldMask` just doesn’t work with `google.protobuf.Struct` at all. Another thing is that we store a JSON struct type in the database as `JSONB` and its GORM mapping is `datatypes.JSON` which is nothing but `[]byte` (i.e., a string).
This commit
- update configuration in model and model_instance from ` google.protobuf.Struct` to string
Note:
This PR relies on #71.
> fix(model): change configuration from struct to string

- openapiv2/openapiv2.swagger.yaml
- vdp/usage/v1alpha/usage.proto
Because
- to constrain the service session data, define service enum type
This commit
- define `service` enum to represent session service
> refactor(usage):  define service enum

- vdp/model/v1alpha/model.proto
Because
- change keypoint message name with plural to make consistency
This commit
- change keypoint message name with plural
> chore: update name of keypoint message to plural for consistency

- vdp/model/v1alpha/model.proto
- vdp/model/v1alpha/model_service.proto
Because
- Add endpoint TriggerModelInstanceBinaryFileUploadResponse for pipeline-backend's usage
This commit
- Add endpoint TriggerModelInstanceBinaryFileUploadResponse
> chore: add trigger model instance binary endpoint

- openapiv2/openapiv2.swagger.yaml
- vdp/model/v1alpha/model_definition.proto
Because
- we need a grading system to represent the readiness level of a model definition 
This commit
- adopt the release stage used in connector definition to model definition
> chore(model): add release stage in model definition

- vdp/model/v1alpha/model.proto
Because
-  naming consistence
This commit
- change name from `bytes` to `content`
> chore(model): update naming

- vdp/model/v1alpha/model.proto
Because
- configuration should represent in the struct, refer to [issue](https://github.com/instill-ai/protobufs/issues/85)
This commit
- change model configuration from string to protobuf struct
> chore(model): change model configuration from string to protobuf struct

- vdp/model/v1alpha/model.proto
Because
- infer model response should be JSON object
This commit
- add output structure of the unspecified task
> chore(model): add unspecified task outputs

- vdp/model/v1alpha/model.proto
Because
- task type should enum
This commit
- update task type of outputs to enum ModelInstance.Task
> chore(mode): update task to enum ModelInstance.Task

- vdp/model/v1alpha/keypoint_output.proto
Because
- key point model also detect person object with bounding box output
This commit
- add bounding box to key point model output
> chore(model): add bounding box object for key point model output

- buf.lock
Because
- old version of googleapis do not exist and error in ci/cd
This commit
- update buf mod deps
> chore: update buf deps version

- vdp/model/v1alpha/model.proto
- vdp/pipeline/v1alpha/pipeline.proto
Because
- naming consistency
This commit
- change BatchOutput to TaskOutput
> refactor(model): change BatchOutput to TaskOutput

- vdp/connector/v1alpha/connector_service.proto
- vdp/mgmt/v1alpha/mgmt_service.proto
- vdp/model/v1alpha/model_service.proto
- vdp/pipeline/v1alpha/pipeline_service.proto
Because
- krakend do not support `:` character in path
This commit
- change `:` to `/` for backend endpoints
> refactor: update endpoint

- vdp/model/v1alpha/instance_segmentation_output.proto
- vdp/model/v1alpha/model.proto
Because
- VDP support instance segmentation task
This commit
- add instance segmentation output task
> feat(model): add instance segmentation task output

- vdp/model/v1alpha/instance_segmentation_output.proto
Because
- we need to keep naming convention strict in protobuf
This commit
- change `InstanceSegmentationObject.label` to `InstanceSegmentationObject.category` in `vdp.model.v1alpha`
> refactor(model): fix field name inconsistency

- vdp/model/v1alpha/model.proto
- vdp/model/v1alpha/semantic_segmentation_output.proto
Because
- support semantic segmentation in VDP
This commit
- add semantic segmentation in model service
> feat(model): add semantic segmentation output

- vdp/pipeline/v1alpha/pipeline.proto
Because
- support semantic segmentation in VDP
This commit
- add semantic segmentation inference output in pipeline backend
> chore(pipeline): add semantic segmentation inference task output

- .github/workflows/add-issue-to-prj.yml
- .github/workflows/add-pr-to-prj.yml
- README.md
- buf.md
Because
- instead of Visual Data Preparation, VDP is Versatile Data Pipeline now. We realise that as a general ETL infrastructure, VDP is capable of processing all kinds of unstructured data, and we should not limit its usage to only visual data. That's why we replace the word Visual with Versatile. Besides, the term Data Preparation is a bit misleading, users often think it has something to do with data labelling or cleaning. The term Data Pipeline is definitely more precise to capture the core concept of VDP.
This commit
- update to Versatile Data Pipeline
> chore: update Visual Data Preparation to Versatile Data Pipeline

- vdp/model/v1alpha/model.proto
Because
- creating a model take quite a long time.
- Note: for creating a local model, it also still takes time to stream the model file or upload the model zip file. Then the API still take long time
This commit
- creating a model asynchronously using Temporal
> chore(model): create a model asynchronously

- vdp/model/v1alpha/model.proto
Because
- `view` is a standard field in the Get/List method in Google AIP
This commit
- add view in the request of Get/List operation methods
> chore: add view in get/list operation methods

- vdp/model/v1alpha/model_service.proto
Because
- check model service ready
This commit
- add additional binding to ready method of model-backend
> chore(model): update ready method with additional binding

- openapiv2/openapiv2.swagger.yaml
- vdp/model/v1alpha/model.proto
- vdp/model/v1alpha/task_classification.proto
- vdp/model/v1alpha/task_detection.proto
- vdp/model/v1alpha/task_instance_segmentation.proto
- vdp/model/v1alpha/task_keypoint.proto
- vdp/model/v1alpha/task_ocr.proto
- vdp/model/v1alpha/task_semantic_segmentation.proto
- vdp/model/v1alpha/task_unspecified.proto
- vdp/pipeline/v1alpha/pipeline.proto
Because
- we are supporting new AI tasks that require different input formats, so we need to define the corresponding input format for each supported AI task explicitly
This commit
- rename task proto files
- add input format for each supported AI task
- refactor the input format for `TriggerModelInstanceRequest` and `TriggerPipelineRequest`
> refactor(model,pipeline): add AI task input format

- vdp/model/v1alpha/model.proto
Because
- typo in TaskInput
This commit
- fix typo
> chore(model): fix typo in TaskInput

- .github/workflows/add-issue-to-prj.yml
- .github/workflows/add-pr-to-prj.yml
Because
- the deprecation of [ProjectNext](https://docs.github.com/en/graphql/reference/objects#projectnext) object and mutations, scheduled for 1st October 2022 [link](https://github.blog/changelog/2022-06-23-the-new-github-issues-june-23rd-update/)
This commit
- reuse [meta workflow](https://github.com/instill-ai/meta)
> ci: update track issue and pr workflows

- vdp/connector/v1alpha/connector.proto
- vdp/model/v1alpha/model.proto
- vdp/model/v1alpha/task_instance_segmentation.proto
- vdp/model/v1alpha/task_semantic_segmentation.proto
- vdp/model/v1alpha/task_unspecified.proto
- vdp/pipeline/v1alpha/pipeline.proto
Because
- the format across files are not consistent
This commit
- reformat all files
- add mixing task input in pipeline
> refactor: auto-format protobuf files

- .github/workflows/buf-check.yaml
- buf.gen.yaml
- buf.lock
- openapiv2/openapiv2.swagger.yaml
- vdp/billing/v1alpha/healthcheck.proto
- vdp/billing/v1alpha/plan.proto
- vdp/billing/v1alpha/plan_service.proto
- vdp/mgmt/v1alpha/mgmt.proto
- vdp/mgmt/v1alpha/mgmt_service.proto
Because
- list, create, update, delete and lookup user operations should be admin API that is not exposed to the public internet
This commit
- add billing service so each user is assigned with a billing plan
- redesign mgmt-backend endpoints into Admin and Public APIs
- update the message user fields
> fix(mgmt,billing): refactor mgmt message, endpoints and add billing service

- openapiv2/openapiv2.swagger.yaml
- vdp/mgmt/v1alpha/mgmt.proto
- vdp/mgmt/v1alpha/mgmt_admin_service.proto
- vdp/mgmt/v1alpha/mgmt_public_service.proto
Because
- we want to separate endpoints into admin (not exposed to public) and public ones
This commit
- make `uid` field immutable
- separate into admin and public services
> fix(mgmt): separate into admin and public services

- openapiv2/openapiv2.swagger.yaml
- vdp/mgmt/v1alpha/mgmt_admin_service.proto
- vdp/mgmt/v1alpha/mgmt_public_service.proto
Because
- we want to name the services concisely
This commit
- rename the mgmt-backend services
- update openapi swagger yaml
> chore: refactor mgmt service names

- vdp/model/v1alpha/task_text_to_image.proto
Because
- wrong type of `guidance scale` in model text to image input
This commit
- change type of `guidance scale` from int64 to float
> chore(model): change type of guidance scale from int to float

- vdp/model/v1alpha/task_text_to_image.proto
Because
- text to image input prompt is required, others fields is optional
This commit
- update text to image input
> chore(model): update text to image input

- vdp/pipeline/v1alpha/pipeline.proto
Because
- unify task input when triggering the model instance
This commit
- update the task input in the pipeline backend for stream method
> chore: update pipeline trigger input stream method

- vdp/metric/v1alpha/metric.proto
- vdp/metric/v1alpha/metric_service.proto
Because
- to support the new metric-backend services that records pipeline and model usages.
This commit
- add protobuf documents defining new metric-backend gRPC services and gRPC messages.
> feat(metric): add protobuf

- openapiv2/openapiv2.swagger.yaml
- vdp/connector/v1alpha/connector_private_service.proto
- vdp/connector/v1alpha/connector_public_service.proto
- vdp/mgmt/v1alpha/mgmt_private_service.proto
- vdp/mgmt/v1alpha/mgmt_public_service.proto
- vdp/model/v1alpha/model_private_service.proto
- vdp/model/v1alpha/model_public_service.proto
- vdp/pipeline/v1alpha/pipeline_private_service.proto
- vdp/pipeline/v1alpha/pipeline_public_service.proto
- vdp/usage/v1alpha/usage_service.proto
Because
- there are many inconsistent comments
This commit
- clean up and unify the discrepant comments
> chore(connector,mgmt,model,pipeline,usage): unify comments

- openapiv2/openapiv2.swagger.yaml
- vdp/connector/v1alpha/connector.proto
- vdp/controller/v1alpha/controller.proto
- vdp/model/v1alpha/model.proto
- vdp/model/v1alpha/model_definition.proto
- vdp/model/v1alpha/model_private_service.proto
- vdp/model/v1alpha/model_public_service.proto
- vdp/pipeline/v1alpha/pipeline.proto
- vdp/usage/v1alpha/usage.proto
Because
- model and model instance concepts make users confused
This commit
- remove the model instance concept and move the state, task from the model instance into the model
- INS-333
> feat(model,pipeline,connector,controller,usage): remove model instance

- openapiv2/openapiv2.swagger.yaml
- vdp/mgmt/v1alpha/mgmt.proto
- vdp/mgmt/v1alpha/mgmt_private_service.proto
- vdp/pipeline/v1alpha/pipeline.proto
- vdp/pipeline/v1alpha/pipeline_public_service.proto
Because
- support public endpoint for pipeline status monitoring
This commit
- add /watch endpoint to pipeline-backend
- fix whitepsaces
> chore(mgmt,pipeline): add public watch method for pipeline state monitoring

- openapiv2/openapiv2.swagger.yaml
- vdp/pipeline/v1alpha/pipeline.proto
Because
- a wrong name for the array field
This commit
- change to plural name for array field
> chore(pipeline): update recipe message

- openapiv2/openapiv2.swagger.yaml
- vdp/controller/v1alpha/controller_service.proto
Because
- missing google api annotations for controller healthcheck
This commit
- add google api annotations for controller healthcheck
> chore(chore): add google api annotations for controller healthcheck

- openapiv2/openapiv2.swagger.yaml
- vdp/model/v1alpha/model.proto
- vdp/model/v1alpha/model_public_service.proto
Because
- the temporal cloud does not support Search Attribute
This commit
- remove unused methods (get, list, cancel operation) using search attribute
> chore(model): remove list, get and cancel operation method

- openapiv2/openapiv2.swagger.yaml
- vdp/connector/v1alpha/connector.proto
- vdp/model/v1alpha/model.proto
- vdp/pipeline/v1alpha/pipeline.proto
Because
- Reduce the query requests to the mgmt-backend to get the owner ID
- The user ID can be changed now (in Instill Cloud), so using the owner ID is not reliable
This commit
- refactor owner of resource to use resource UUID, not resource ID
> chore(mgmt,pipeline,connector): return owner uuid instead of id

- openapiv2/openapiv2.swagger.yaml
- vdp/mgmt/v1alpha/mgmt.proto
- vdp/mgmt/v1alpha/mgmt_private_service.proto
Because
- Because `expires_in` has same meaning as `lifetime`, change it to `expires_at` will be more friendly.
This commit
- change `expires_in` to `expires_at`
- remove ValidateToken()
> chore(mgmt): change expires_in to expires_at, remove ValidateToken()

- openapiv2/openapiv2.swagger.yaml
- vdp/mgmt/v1alpha/mgmt.proto
Because
- According to Google [AIP](https://google.aip.dev/214), we should provide both `ttl` and `expire_time` for resource expiration.
This commit
- Add `ttl` and `expire_time` in mgmt ApiToken protobuf
> chore(mgmt): change token `lifetime` to `ttl`

- openapiv2/openapiv2.swagger.yaml
- vdp/connector/v1alpha/connector.proto
- vdp/connector/v1alpha/connector_private_service.proto
- vdp/controller/v1alpha/controller.proto
- vdp/controller/v1alpha/controller_service.proto
- vdp/model/v1alpha/model.proto
- vdp/model/v1alpha/model_private_service.proto
- vdp/pipeline/v1alpha/pipeline.proto
- vdp/pipeline/v1alpha/pipeline_private_service.proto
Because
- allow same resource name under different user namespace
This commit
- update controller resource name to uuid
- remove Get admin API in connector/pipeline/model backends
> chore(controller,connector,pipeline,model): update controller and remove Get admin api

- openapiv2/openapiv2.swagger.yaml
- vdp/pipeline/v1alpha/pipeline.proto
Because
- We are planning to support DAG pipeline. The original pipeline recipe format can not cover the complex DAG pipeline. We design a new recipe which is consists of list of components. Every component represent a node in a graph, these node can be model or connector.
This commit
- update the recipe format
> chore(pipeline): update dag recipe format

- openapiv2/openapiv2.swagger.yaml
- vdp/connector/v1alpha/connector.proto
- vdp/connector/v1alpha/connector_public_service.proto
- vdp/pipeline/v1alpha/pipeline.proto
Because
- update /check endpoint to be sync
- add /test endpoint for on demand connector state check
This commit
- remove longrunning operation related endpoint
- update /check to return state instead of workflow id
- add /test endpoint in connector-backend for on demand state check
> chore(connector): remove longrunning operation and add custome test method

- openapiv2/openapiv2.swagger.yaml
- vdp/pipeline/v1alpha/pipeline.proto
- vdp/pipeline/v1alpha/pipeline_public_service.proto
Because
- Use the same endpoint for sync/async trigger is not good. We need to separate them.
This commit
- separate pipeline trigger to sync and async two endpoints
> chore(pipeline): separate pipeline trigger to sync and async endpoints

- openapiv2/openapiv2.swagger.yaml
- vdp/connector/v1alpha/connector_public_service.proto
Because
- use POST for potential resource state change in system
This commit
- update test connection method type to POST
> chore(connector): fix testConnection method type

- openapiv2/openapiv2.swagger.yaml
- vdp/connector/v1alpha/connector.proto
- vdp/connector/v1alpha/connector_public_service.proto
Because
- As a component in the pipeline, the connector is a module that responsible for transforming data. We add a `DataPayload` message to unify the data format flow from source to destination.
This commit
- add a `DataPayload` message to define the data format in pipeline
- refactor `ReadSourceConnector`, `WriteDestinationConnector` to `ExecuteSourceConnector`, `ExecuteDestinationConnector`
> chore(connector): add DataPayload message for pipeline and Execute interface

- openapiv2/openapiv2.swagger.yaml
- vdp/connector/v1alpha/connector.proto
- vdp/connector/v1alpha/connector_definition.proto
- vdp/connector/v1alpha/connector_private_service.proto
- vdp/connector/v1alpha/connector_public_service.proto
Because
- the original source-connectors/destination-connectors endpoints are basically the same. And since we will have more types of connector in the future. Adding more endpoints is not a good choices.
- we will have public connectors that can be used for all people.
This commit
- unified this endpoints and use `filter` to search different type of connectors
- refactor the nested structure of `connector` and `connector_definition` message
- add visibility field for setting public/private connectors
> chore(connector): refactor `source|destination- connector/*` endpoints to `connectors/*` endpoints

- openapiv2/openapiv2.swagger.yaml
- vdp/connector/v1alpha/connector.proto
- vdp/connector/v1alpha/connector_definition.proto
Because
- we need a better naming for connector type and payload, or the user will be confused
This commit
- rename `json` to `structured_data`
- rename `CONNECTOR_TYPE_MODEL` to `CONNECTOR_TYPE_AI`
> chore(connector): rename `json` to `structured_data` and `CONNECTOR_TYPE_MODEL` to `CONNECTOR_TYPE_AI`

- base/mgmt/v1alpha/metric.proto
- base/mgmt/v1alpha/mgmt_public_service.proto
- openapiv2/openapiv2.swagger.yaml
Because
- support getting pipeline trigger records
This commit
- add `ListPipelineTriggerRecord` method in `mgmt`
> chore(mgmt): add pipeline metric methods

- openapiv2/openapiv2.swagger.yaml
- vdp/pipeline/v1alpha/pipeline.proto
- vdp/pipeline/v1alpha/pipeline_public_service.proto
Because
- The original pipeline input is task-specific, which is not good for complex DAG pipeline.
This commit
- refactor the pipeline input as a general data payload
> chore(pipeline): add PipelineDataPayload and update TriggerSyncPipelineRequest/Response

- openapiv2/openapiv2.swagger.yaml
- vdp/connector/v1alpha/connector.proto
Because
- currently, the frontend need to call api twice to get the complete info for connector and its definition
This commit
- provide a field that can embed the `ConnectorDefinition` in `Connector`
> chore(connector): embed the ConnectorDefinition detail in Connector when VIEW_FULL

- openapiv2/openapiv2.swagger.yaml
- vdp/pipeline/v1alpha/pipeline.proto
Because
- we already have `data_mapping_index` inside `PipelineDataPayload`, so the `data_mapping_indices` is no needed
This commit
- remove redundant data_mapping_indices fields
> chore(pipeline): remove redundant data_mapping_indices fields

- base/mgmt/v1alpha/metric.proto
- openapiv2/openapiv2.swagger.yaml
Because
- fix metric method field name
This commit
- fix metric method field name
> chore(mgmt): fix metric method field name

- model/model/v1alpha/model.proto
- model/model/v1alpha/model_private_service.proto
- openapiv2/openapiv2.swagger.yaml
Because
- allow controller to deploy/undeploy when current state deviate from desire state
This commit
- add admin deploy/undeploy endpoint in model
> chore(model): add admin deploy/undeploy endpoint in model

- base/mgmt/v1alpha/metric.proto
- openapiv2/openapiv2.swagger.yaml
- vdp/pipeline/v1alpha/pipeline.proto
- vdp/pipeline/v1alpha/pipeline_public_service.proto
Because
- the sync/async terms are not user-friendly
This commit
- remove pipeline mode
- rename the get long running operation endpoint
- rename `triggerSync` to `trigger`
> chore(pipeline): remove pipeline mode and rename sync async endpoints

- openapiv2/openapiv2.swagger.yaml
- vdp/connector/v1alpha/connector.proto
- vdp/pipeline/v1alpha/pipeline.proto
Because
- we should add a connector `Task` enums to define the available `Task` for our connectors. The `Task` will be not only AI task, but also other tasks such as data task, blockchain task...etc
This commit
- remove unused `TaskOutput` in pipeline
- add `Type` in connector
> chore(pipeline,connector): remove unused TaskOutput in pipeline, add Type in connector

- base/mgmt/v1alpha/metric.proto
- base/mgmt/v1alpha/mgmt_public_service.proto
- openapiv2/openapiv2.swagger.yaml
Because
- support aggregation time bucket methods for dashboard chart render
- support connector dashboard
This commit
- add connector metric methods
- add list chart method for pipeline trigger
> chore(metric): add connector and chart metric methods

- base/mgmt/v1alpha/metric.proto
- base/mgmt/v1alpha/mgmt_public_service.proto
- openapiv2/openapiv2.swagger.yaml
Because
- support table view with pagination for pipeline/connector
This commit
- add list table records endpoints for pipeline and connector
> chore(mgmt): add list table metric endpoints

- openapiv2/openapiv2.swagger.yaml
- vdp/connector/v1alpha/connector_definition.proto
Because
- We are going to merge source/destination connectors into data connectors
This commit
- add new `ConnectorType`: `CONNECTOR_TYPE_DATA` and `CONNECTOR_TYPE_OPERATOR`
> chore(connector): add new ConnectorType

- base/usage/v1alpha/usage.proto
- openapiv2/openapiv2.swagger.yaml
Because
- lack details in current usage data collection
This commit
- add model/connector/pipeline trigger/execute metadata in usage report
> chore(usage): add trigger/execute metadata in usage report

- openapiv2/openapiv2.swagger.yaml
- vdp/connector/v1alpha/connector.proto
- vdp/connector/v1alpha/spec.proto
- vdp/pipeline/v1alpha/pipeline.proto
Because
- We want to make the data input/output format more flexible, the DataPayload and PipelineDataPayload is not need for the new component-centric design
This commit
- retire DataPayload and PipelineDataPayload
- retire dependency field in pipeline recipe component
> chore(connector,pipeline): retire DataPayload and PipelineDataPayload

- openapiv2/openapiv2.swagger.yaml
- vdp/connector/v1alpha/connector_definition.proto
- vdp/connector/v1alpha/connector_private_service.proto
- vdp/pipeline/v1alpha/operator_definition.proto
- vdp/pipeline/v1alpha/pipeline.proto
- vdp/pipeline/v1alpha/pipeline_private_service.proto
- vdp/pipeline/v1alpha/pipeline_public_service.proto
Because
- we need a api to list all of our operator definitions
- need to update recipe format for component centric design
This commit
- add operator_definitions endpoints
- update recipe format
> chore(connector,pipeline): add operator_definitions endpoints and update recipe format

- base/usage/v1alpha/usage.proto
- openapiv2/openapiv2.swagger.yaml
Because
- avoid complex query requirement for usage metric
This commit
- add `owner_uid` in `session`
> chore(usage): add owner_uid to session

- model/model/v1alpha/model.proto
- openapiv2/openapiv2.swagger.yaml
Because
- adopt changes in `model-backend` that public deploy/undeploy only change the desire state of the model
This commit
- update public deploy/undeploy response to be `model`
> chore(model): update public deploy/undeploy to change desire state only

- openapiv2/openapiv2.swagger.yaml
- vdp/pipeline/v1alpha/pipeline.proto
Because
- we need to return the trace data for each component when we want to debug the pipeline
This commit
- add `Traces` data in pipeline response
> chore(pipeline): add Traces data in pipeline response

- openapiv2/openapiv2.swagger.yaml
- vdp/controller/v1alpha/controller.proto
- vdp/pipeline/v1alpha/pipeline.proto
- vdp/pipeline/v1alpha/pipeline_private_service.proto
- vdp/pipeline/v1alpha/pipeline_public_service.proto
Because
- we need to have release and version control for pipeline
This commit
- add pipeline release endpoints
> chore(pipeline): add pipeline release endpoints

- openapiv2/openapiv2.swagger.yaml
- vdp/connector/v1alpha/connector.proto
- vdp/connector/v1alpha/connector_definition.proto
- vdp/connector/v1alpha/connector_public_service.proto
- vdp/pipeline/v1alpha/pipeline.proto
- vdp/pipeline/v1alpha/pipeline_public_service.proto
Because
- We would like to make the resources be public or shared to other users. The current structure can not support it since the api endpoint was designed for the users' own resources.
This commit
- add namespace for api endpoints
> chore(pipeline,connector): add namespace for api endpoints

- model/model/v1alpha/model.proto
- model/model/v1alpha/model_public_service.proto
- openapiv2/openapiv2.swagger.yaml
Because
- We would like to make the resources be public or shared to other
users. The current structure can not support it since the api endpoint
was designed for the users' own resources.
This commit
- add namespace for model api endpoints
> chore(model): add namespace for model api endpoints

- openapiv2/openapiv2.swagger.yaml
- vdp/connector/v1alpha/connector.proto
- vdp/connector/v1alpha/connector_public_service.proto
- vdp/pipeline/v1alpha/pipeline.proto
- vdp/pipeline/v1alpha/pipeline_public_service.proto
Because
- We use `uuid` in lookup endpoint. `uuid` is unique so we don't need the namespace. 
This commit
- remove namespace in lookup endpoints
> chore(pipeline,connector): remove namespace in lookup endpoints

- model/model/v1alpha/model.proto
- model/model/v1alpha/model_public_service.proto
- openapiv2/openapiv2.swagger.yaml
Because
- We use `uuid` in lookup endpoint. `uuid` is unique so we don't need
the namespace.
This commit
- remove namespace in lookup endpoints
> chore(model): remove namespace in lookup endpoint

- openapiv2/openapiv2.swagger.yaml
- vdp/pipeline/v1alpha/common.proto
- vdp/pipeline/v1alpha/pipeline.proto
Because
- we'll generate openapi_schema for each pipeline trigger automatically
- we need a intermediate view mode between `VIEW_BASIC` and `VIEW_FULL`
This commit
- add `openapi_schema` field in pipeline
- add `VIEW_RECIPE`
> chore(pipeline): add openapi_schema field in pipeline and add VIEW_RECIPE

- openapiv2/openapiv2.swagger.yaml
- vdp/pipeline/v1alpha/pipeline.proto
Because
- the `openapi_schema` should be a struct, not array of struct
This commit
- fix `openapi_schema` wrong type
> chore(pipeline): fix openapi_schema wrong type

- openapiv2/openapiv2.swagger.yaml
- vdp/pipeline/v1alpha/pipeline_public_service.proto
Because
- remove the constraint that only default pipeline release can be watched
This commit
- allow watch endpoint for all pipeline releases
> chore(pipeline): allow watch endpoint for all pipeline releases

- buf.gen.yaml
Because
- provide better type checking, comments as docstrings and enum type wrapper
This commit
- add mypy plugins
> chore(plugin): add mypy plugins

- openapiv2/openapiv2.swagger.yaml
- vdp/connector/v1alpha/connector_definition.proto
Because
- Currently `VIEW_FULL` will return both `configuration` and `connector_definition`, we need a new view mode to return `configuration` only
This commit
- Add `VIEW_CONFIGURATION`
> chore(connector): add `VIEW_CONFIGURATION`

- openapiv2/openapiv2.swagger.yaml
- vdp/pipeline/v1alpha/pipeline_public_service.proto
Because
- we should use camelCase
This commit
- fix case for set_default endpoint
> chore(pipeline): fix case for set_default endpoint

- base/mgmt/v1alpha/mgmt.proto
- base/mgmt/v1alpha/mgmt_public_service.proto
- openapiv2/openapiv2.swagger.yaml
Because
- we need a endpoint to validate the `api_token`
This commit
- add token validation endpoint
> chore(mgmt): add token validation endpoint

- base/mgmt/v1alpha/metric.proto
- base/usage/v1alpha/usage.proto
- openapiv2/openapiv2.swagger.yaml
Because
- adopt pipeline release feature for usage and metric data
This commit
- adopt pipeline release feature for usage and metric data
> chore(usage,metric): adopt pipeline release in usage and metric data

- model/model/v1alpha/model.proto
- openapiv2/openapiv2.swagger.yaml
- vdp/connector/v1alpha/connector.proto
- vdp/pipeline/v1alpha/pipeline.proto
Because
- we need to have a way to return soft-deleted resources
This commit
- add `show_deleted` param to return soft-deleted resources
> chore(pipeline,connector,model): add `show_deleted` param to return soft-deleted resources

- base/mgmt/v1alpha/mgmt.proto
- base/mgmt/v1alpha/mgmt_public_service.proto
- openapiv2/openapiv2.swagger.yaml
Because
- we need to provide simple authentication in Instill-Core
This commit
- add auth endpoints: `/auth/login`, `/auth/logout`, `/auth/validate_access_token`, `/auth/change_password`
> chore(mgmt): add auth endpoints

- openapiv2/openapiv2.swagger.yaml
- vdp/connector/v1alpha/spec.proto
- vdp/pipeline/v1alpha/operator_definition.proto
Because
- the `operator_definitions` also need `spec.openapi_specifications` to describe input/output format
This commit
- add `spec.openapi_specifications` in `operator_definitions`
> chore(connector,pipeline): add `spec.openapi_specifications` in `operator_definitions`

- openapiv2/openapiv2.swagger.yaml
- vdp/pipeline/v1alpha/pipeline.proto
Because
- we need a field to indicate the `pipeline_release` alias name
This commit
- add `alias` field into pipeline_release payload
> chore(pipeline): add `alias` field into `pipeline_release` payload

- openapiv2/openapiv2.swagger.yaml
- vdp/connector/v1alpha/connector.proto
Because
- the `task` field decide the input and output format, it should be outside of the `inputs` field
This commit
- add `task` field in ExecuteUserConnector request
> chore(connector): add `task` field in ExecuteUserConnector request

- openapiv2/openapiv2.swagger.yaml
- vdp/pipeline/v1alpha/pipeline.proto
Because
- we want to store layout of pipeline builder in backend.
This commit
- add `metadata` field in pipeline and pipeline_release payload
> chore(pipeline): add `metadata` field in pipeline payload

- model/model/v1alpha/task_text_to_image.proto
- openapiv2/openapiv2.swagger.yaml
Because
- to support image-to-image before [INS-2574](https://linear.app/instill-ai/issue/INS-2574/make-ai-tasks-consistent) complete
This commit
- add two new fields on text0to-image task
> chore(model): add image and extra_params for textToImage Task

- core/mgmt/v1alpha/mgmt.proto
- core/mgmt/v1alpha/mgmt_private_service.proto
- openapiv2/openapiv2.swagger.yaml
- vdp/pipeline/v1alpha/connector.proto
- vdp/pipeline/v1alpha/connector_definition.proto
- vdp/pipeline/v1alpha/operator_definition.proto
- vdp/pipeline/v1alpha/pipeline.proto
- vdp/pipeline/v1alpha/pipeline_public_service.proto
Because
- we need to allow user to create pipeline/connector under organization under organization namespace
This commit
- support creating pipeline/connector under organization
- add organization admin endpoints
> chore(base,vdp): support creating pipeline/connector under organization

- core/mgmt/v1alpha/mgmt.proto
- openapiv2/openapiv2.swagger.yaml
Because
- we need to store the user avatar and profile data
This commit
- add profile avatar and data fields
> chore(mgmt): add profile avatar and data fields

- openapiv2/openapiv2.swagger.yaml
- vdp/pipeline/v1alpha/common.proto
Because
- we need a new pipeline sharing role to allow user trigger the public pipeline
This commit
- add new pipeline sharing role: `ROLE_EXECUTOR`
> chore(vdp): add new pipeline sharing role

- core/mgmt/v1alpha/mgmt.proto
- core/mgmt/v1alpha/mgmt_public_service.proto
- openapiv2/openapiv2.swagger.yaml
Because
- we need an API to determine the availability of a namespace id and its type
This commit
- remove ExistUsername API  and add new CheckNamespace API
> chore(core): remove ExistUsername API  and add new CheckNamespace API

- core/mgmt/v1beta/mgmt_public_service.proto
- openapiv2/openapiv2.swagger.yaml
Because
- we are going to release beta version of Core and VDP
This commit
- upgrade CheckNamespace endpoint version to v1beta
> chore(core): upgrade CheckNamespace endpoint version to v1beta

- core/usage/v1beta/usage.proto
- openapiv2/openapiv2.swagger.yaml
Because
- differentiate `orgs` and `users` type trigger data
This commit
- add type for `user` and `owner` for each resource
> chore(usage): add owner and user type in resource data

- model/model/v1alpha/model.proto
- openapiv2/openapiv2.swagger.yaml
- vdp/pipeline/v1beta/connector.proto
- vdp/pipeline/v1beta/pipeline.proto
Because
- we need to embed more data in response payload to reduce the API round trip
This commit
- embed owner profile data in pipeline, connector, model payload
- embed releases data in pipeline payload
> chore(all): embed owner profile data in pipeline, connector, model payload

- core/mgmt/v1beta/mgmt.proto
- core/mgmt/v1beta/mgmt_public_service.proto
- openapiv2/openapiv2.swagger.yaml
Because
- we'd like to simplify the message of CheckNamespaceRequest
This commit
- refactor CheckNamespace endpoint
- fix comment
> chore(core): refactor CheckNamespace endpoint and fix comment

- openapiv2/openapiv2.swagger.yaml
- vdp/pipeline/v1beta/pipeline.proto
Because
- we'll support conditional component, so we must show the actual status of each component
This commit
- add status in pipeline traces data
> chore(vdp): add status in pipeline traces data

- openapiv2/openapiv2.swagger.yaml
- vdp/pipeline/v1beta/pipeline.proto
Because
- we need to store pipeline `readme` data
This commit
- add pipeline `readme` field
> chore(vdp): add pipeline readme field

- core/mgmt/v1beta/mgmt.proto
- openapiv2/openapiv2.swagger.yaml
Because
- we need to embed owner information in the organization payload
This commit
- add owner field in organization payload
> chore(mgmt): add owner field in organization payload

- openapiv2/openapiv2.swagger.yaml
- vdp/pipeline/v1beta/common.proto
- vdp/pipeline/v1beta/pipeline.proto
Because
- We are going to refactor `pipeline.permission` as the corresponding permission of the authenticated user. And the original pipeline permission setting will now be `pipeline.sharing`
This commit
- refactor `pipeline.permission` and `pipeline.sharing`
> chore(vdp): refactor `pipeline.permission` and `pipeline.sharing`

- model/model/v1alpha/common.proto
- model/model/v1alpha/task_image_to_image.proto
- model/model/v1alpha/task_text_generation.proto
- model/model/v1alpha/task_text_generation_chat.proto
- model/model/v1alpha/task_text_to_image.proto
- model/model/v1alpha/task_visual_question_answering.proto
- openapiv2/openapiv2.swagger.yaml
Because ... 
- This update is necessitated by the need to align our current text-generation-task schema more closely with OpenAI's task structure.
This commit .. 
1. **Enhancement of TASK_TEXT_GENERATION**: Following our discussion in [INS-2982](https://linear.app/instill-ai/issue/INS-2982/harmonizing-the-text-generation-tasks-protocol-buffer-with-the-openai), we have introduced three new fields to the `TASK_TEXT_GENERATION` protocol buffer:
- An optional `admin_message` string.
- An optional `chat_history` field, now mirroring the type used in `conversation`.
- An optional `image_url` string, which is a base64 encoded string including batch dimension.
2. **Improved `extra_param` Support**: To offer enhanced functionality for the `extra_param`, we have implemented the suggestions in …
> feat(model): Update Text-Generation Task Schema to Align with OpenAI Standards

- .github/workflows/buf-gen-openapi.yaml
- common/openapi/v1beta/options.proto
- core/mgmt/v1beta/mgmt.proto
- openapiv2/openapiv2.swagger.yaml
- vdp/pipeline/v1beta/connector.proto
- vdp/pipeline/v1beta/pipeline.proto
Because
- We want to publish our docs in readme.io
- The upload step fails on validation (against `swagger-cli`)
This commit
- Updates the proto definitions to produce a valid OpenAPI output
- Updates the GHA linter
Validation errors:
```
> swagger-cli validate openapiv2/openapiv2.swagger.yaml
Swagger schema validation failed.
#/host must match pattern "^[^{}/ :\\]+(?::\d+)?$"
Property 'connector' listed as required but does not exist in '/paths/v1beta/{organization.name}/connectors/post/parameters/connector'
Property 'connector' listed as required but does not exist in '/paths/v1beta/{organization.name}/connectors/post/parameters/connector'
Property 'pipeline' listed as required but does not exist in '/paths/v1beta/{organization.name}/pipelines/post/parameters/pipeline'
Property …
```
> docs(openapi): Validate OpenAPI against readme.io validator

- openapiv2/openapiv2.swagger.yaml
- vdp/pipeline/v1beta/pipeline.proto
Because
- Currently, we have the `ListPipelines` API that returns all the pipelines to which the user has permissions. However, in the Instill Hub, we only want to list the public pipelines that all users have permission to access. Instead of introducing a new API, we have decided to use a query parameter to limit the results.
This commit
- add `Visibility` enum in pipeline message
- add `Visibility` param in the request of `ListPipelines`
> chore(pipeline): add `Visibility` enum in pipeline

- core/mgmt/v1beta/mgmt.proto
- openapiv2/core/service.swagger.yaml
- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/connector.proto
- vdp/pipeline/v1beta/connector_definition.proto
- vdp/pipeline/v1beta/operator_definition.proto
- vdp/pipeline/v1beta/pipeline.proto
- vdp/pipeline/v1beta/pipeline_public_service.proto
Because
- Path parameters aren't read correctly, e.g.
`/vdp/v1beta/{operator_definition.name}` -> `/vdp/v1beta/%7Boperator_definition.name%7D`
This commit
- Updates the path param names to remove dots, which break the rendering in
readme.io
When trying to make use of the `curl` console the website escapes the
characters. This doesn't prevent the user from making the API call but results in an ugly cURL command. Other callers like Node don't escape the slashes.
> docs(openapi): fix path param rendering in readme.io

- model/model/v1alpha/model.proto
- model/model/v1alpha/model_public_service.proto
- openapiv2/model/service.swagger.yaml
Because
- we need to support creating models under organization namespace
- we no longer need test related endpoints for model
This commit
- support creating models under organization
- retire test related endpoints
> chore(model): add organization endpoints and retire test endpoints

- model/controller/v1alpha/controller.proto
- openapiv2/model/service.swagger.yaml
Because
- model-backend needs to be able to retrieve workflowid with `GetResource`
This commit
- move workflowid field into resource message
> chore(model): move workflowid into resource

- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/pipeline.proto
Because
- We want to let user query user and organization pipelines with `visibility`
This commit
- add visibility param for `ListUserPipelines` and `ListOrganizationPipelines` endpoints
> feat(vdp): add visibility param for list pipelines endpoints

- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/pipeline.proto
- vdp/pipeline/v1beta/pipeline_public_service.proto
Because
- We want to provide an API to let user clone the pipeline recipe.
This commit
- Add `CloneUserPipeline` and `CloneOrganizationPipeline` endpoints
> feat(vdp): add `CloneUserPipeline` and `CloneOrganizationPipeline` endpoints

- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/common.proto
- vdp/pipeline/v1beta/pipeline_public_service.proto
Because
- We want to provide an endpoint to let Console check the availability of pipeline or connector name.
This commit
- Add `CheckName` endpoint
> feat(vdp): add CheckName endpoint

- model/model/v1alpha/model_public_service.proto
- openapiv2/model/service.swagger.yaml
- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/common.proto
- vdp/pipeline/v1beta/connector.proto
- vdp/pipeline/v1beta/pipeline.proto
- vdp/pipeline/v1beta/pipeline_public_service.proto
Because
- New endpoints use a different convention for specifying the format of a field than the previously documented endpoints.
- E.g.: `organizations/<org_id>/pipelines/<pipeline_id>` vs [`organizations/{organization.id}/pipelines/{pipeline.id}`](https://github.com/instill-ai/protobufs/blob/main/vdp/pipeline/v1beta/pipeline.proto#L860).
This commit
- Unifies the convention.
- Fixes a typo due to copypaste (a organization -> an organization)
cc @donch1989 I hope this PR doesn't read as nitpicky 😅 It's hard to enforce these conventions by e.g. linter but I think having consistency in our docs is good for the public image of Instill AI. I'd say the best way to keep consistent at this point is relying on existing documentation and on peer reviews (I doubt product / marketing will QA …
> docs(openapi): Align new endpoints with existing ones

- core/mgmt/v1beta/mgmt.proto
- core/mgmt/v1beta/mgmt_public_service.proto
- openapiv2/core/service.swagger.yaml
Because
- Some user information is sensitive and should not be accessed by other users.
- We didn't return the onboarding process status, making it difficult for the Console to handle the user onboarding workflow.
This commit
- Adds a new `GetAuthenticatedUser` endpoint for getting authenticated users' own data.
- Introduces the `OnboardingStatus` enum to indicate the status of the onboarding process.
- Removes sensitive data from the responses of `GetUser` and `ListUsers`.
- Changes `org_name` in `User` to `company_name` to prevent confusion.
> feat(mgmt): refactor APIs for `Get` and `Patch` authenticated user

- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/common.proto
- vdp/pipeline/v1beta/connector_definition.proto
- vdp/pipeline/v1beta/operator_definition.proto
Because
- Basic connector / operator definition view doesn't contain the information
needed to render a summary of the available tasks at Instill AI
Design in Figma [here](https://www.figma.com/file/M4vNxW6o4FCs9qSvmUuin1/Landing-Page?type=design&mode=design&t=WE3uddPT5jA4Shj1-0).
This commit
- Extends the connector and operator definition information with fields that
will be used to render a summary of the available components and tasks.
- Component version
- Available tasks
- Source code URL
> feat(vdp): extend component definitions

- core/mgmt/v1beta/mgmt.proto
- core/mgmt/v1beta/mgmt_public_service.proto
- openapiv2/core/service.swagger.yaml
Because
- Initially, the `profile_data` is a free-form structure and is not well-documented, making it challenging to create comprehensive documentation.
- We aim to integrate Stripe subscription information into the subscription endpoints.
This commit
- Introduces `UserProfile` and `OrganizationProfile` messages to describe the profile data.
- Incorporates Stripe subscription information in the subscription responses.
- Adds `cookie_token` back since Console still need it for tracking user.
> feat(mgmt): refactor user/org profile and subscription endpoints

- core/usage/v1beta/usage.proto
- openapiv2/core/service.swagger.yaml
Because
- the new `artifact` project has usage data to collect
This commit
- add preliminary protobuf
> feat(usage): add artifact usage data

- artifact/artifact/v1alpha/artifact.proto
- artifact/artifact/v1alpha/artifact_public_service.proto
- openapiv2/artifact/service.swagger.yaml
Because
- to initiate `artifact` services
This commit
- add basic `liveness` and `readiness`
> feat(artifact): add services

- core/mgmt/v1beta/mgmt.proto
- openapiv2/core/service.swagger.yaml
Because
- We need the `status` and `trial_end` data from Stripe.
This commit
- adds Stripe's `status` enum and `trial_end` field.
Note
- [Reference for the enum](https://stripe.com/docs/api/subscriptions/object#subscription_object-status)
> feat(mgmt): add Stripe `status` and `trial_end`

- core/usage/v1beta/usage.proto
- openapiv2/core/service.swagger.yaml
Because
- We removed some onboarding data from `User` message and put them in the `AuthenticatedUser` message. Thus, we should use `AuthenticatedUser` to collect the usage data.
This commit
- Uses `AuthenticatedUser` message in usage collection.
> feat(usage): use `AuthenticatedUser` message in usage collection

- .github/workflows/sync-api-docs.yml
Because
- OpenAPI changes require manual uploads in ReadMe.com
- We have no staging docs
This commit
- Syncs the `main` branch with the public and private version of the API
- Changes in main branch update the staging docs
- Version changes in main branch update the public docs
I created [a playground environment](https://github.com/jvallesm/instill-protobufs) to test the GitHub actions:
- See the [README](https://github.com/jvallesm/instill-protobufs) for a more detailed explanation.
- Workflow run [without version changes](https://github.com/jvallesm/instill-protobufs/actions/runs/7899195585/job/21558124375).
- Workflow run [with version changes](https://github.com/jvallesm/instill-protobufs/actions/runs/7899206790).
✅  This PR will need:
> feat(openapi): keep public and private API docs in sync with main branch

- core/mgmt/v1beta/mgmt.proto
- model/model/v1alpha/model.proto
- openapiv2/model/service.swagger.yaml
- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/connector.proto
- vdp/pipeline/v1beta/pipeline.proto
Because:
- Originally, we used `owner_name` and `owner` (`structpb`) to embed owner information for Console. However, `owner` is a `structpb`, and it is not well-formatted. Since we already have dedicated messages for `User` and `Organization`, we should utilize these messages.
This commit:
- Adds a new `Owner` message to wrap the `User` and `Organization` messages.
- Removes  `owner` in resource response.
- Marks `owner_name` in resource response as deprecated. Once the frontend removes it, we'll remove it as well.
> feat(core): add `Owner` message for embedding user and organization information

- core/mgmt/v1beta/mgmt.proto
- openapiv2/core/service.swagger.yaml
- vdp/pipeline/v1beta/common.proto
- vdp/pipeline/v1beta/component_definition.proto
Because
- We want to display additional description about the subscription.
This commit
- Adds description field in subscription response.
> feat(mgmt): add description field in subscription response

- common/openapi/v1beta/api_config.conf
- openapiv2/core/service.swagger.yaml
- openapiv2/model/service.swagger.yaml
- openapiv2/vdp/service.swagger.yaml
Because
- As `grpc-gateway` only supports OpenAPI 2.x, we were relying on the
field description to specify `Bearer` is part of the API key.
This commit
- Adds a [readme.com extension](https://docs.readme.com/main/docs/openapi-extensions#authentication-defaults) to display an auth example
> fix(openapi): add readme.com extension for showing "Bearer" in auth

- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/component_definition.proto
Because
- Component page needs to receive the `description` field in the component `definitions.json`
This commit
- Exposes the description in the `Connector` and `Operator` proto entities.
```sh
$ curl --request GET \
--url "localhost:8080/vdp/v1beta/component-definitions?page=1" \
--header 'accept: application/json' | jq '.component_definitions[7]'
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  7683    0  7683    0     0   357k      0 --:--:-- --:--:-- --:--:--  375k
{
"type": "COMPONENT_TYPE_OPERATOR",
"operator_definition": {
"name": "operator-definitions/json",
"uid": "28f53d15-6150-46e6-99aa-f76b70a926c0",
"id": "json",
"title": "JSON",
"documentation_url": …
```
> feat(vdp): add description field to component definitions

- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/connector.proto
- vdp/pipeline/v1beta/pipeline.proto
Because:
- The original recipe message utilized `structpb` to encapsulate every configuration, creating an implicit structure that posed a challenge for users or developers to comprehend the data structure. Given the distinct structures associated with various components, it is essential to explicitly expose them to the user.
- A special iterator component for array data iteration is desired.
This commit:
- Revamped the recipe messages by introducing new messages: `StartComponent`, `EndComponent`, `OperatorComponent`, `ConnectorComponent`, and `IteratorComponent`.
Note:
- This is a breaking change in the interface, requiring an update to the implementation on the client-side.
> feat(vdp): revamp pipeline recipe and introduce iterator component

- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/component_definition.proto
- vdp/pipeline/v1beta/pipeline.proto
Because
- Currently, we have an `openapi_specification` field in the pipeline and connector/operator definition. The original purpose was that we could generate an OpenAPI schema and have some UI to let the user debug on an individual component. However, it turns out that we don't really need that OpenAPI schema, and it makes our response very large and hard to read. 
This commit
- Simplifies `openapi_specification` into `data_specification` by preserving only the input and output JSON schema and removing the nested structure of the OpenAPI spec.
- Adds `data_specifications` in iterator component.
> feat(vdp): remove openapi_specification and add data_specification

- artifact/artifact/v1alpha/artifact.proto
- artifact/artifact/v1alpha/artifact_private_service.proto
- artifact/artifact/v1alpha/artifact_public_service.proto
- openapiv2/artifact/service.swagger.yaml
- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/pipeline.proto
Because
- We want to list the versions of a model.
- Registry has a [tags](https://distribution.github.io/distribution/#listing-image-tags) endpoint but it doesn't expose any timestamp.
This commit
- Adds and documents a private API for the repository tags in artifact.
- Only `api-gateway` (when it detects the end of the image push operation) should communicate the creation of a tag.
- The tags won't be exposed directly to the client. `model-backend` will request this information to expose the model versions in the same family as the rest of the model endpoints.
As an initial addition to the Artifact domain, I made some naming choices. Please review and provide feedback about them.
- `artifact-backend` will implement a first version of this endpoint that will fetch the tag list from the …
> feat(artifact): add tag create / list endpoints

- artifact/artifact/v1alpha/artifact.proto
- artifact/artifact/v1alpha/artifact_private_service.proto
- model/model/v1alpha/model.proto
- openapiv2/model/service.swagger.yaml
Because
- We'd like to provide more information to model state
This commit
- add message field in watch response
> chore(model): add message in watch endpoint

- artifact/artifact/v1alpha/artifact.proto
- openapiv2/artifact/service.swagger.yaml
Because
- optional fields in `RepositoryTag` should be documented. The backend will return a successful `List` response even when these aren't present.
- `digest` ins't output-only. It will be set in the `Create` endpoint.
This commit
- updates the protobuf definition with the right field behaviours.
> feat(artifact): document optional tag fields

- artifact/artifact/v1alpha/artifact.proto
Because
- `parent` param is redundant with `tag.name`.
This commit
- Removes param.
> fix(artifact): remove unnecessary parent param in tag creation

- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/pipeline.proto
Because
- We are designing a new trigger field to allow users to set up different trigger methods. As a result, we are going to retire the original start component and incorporate it into the trigger method.
This commit
- Removes "start component".
- Adds "trigger" field with "trigger_by_request" method.
- Renames "end component" to "response component".
> feat(vdp): revamp start component and end component

- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/pipeline.proto
Because
- We've retired `Connector`, but we still need a place to store connection configuration.
This commit
- Adds `connection` field in `ConnectorComponent`.
> feat(vdp): add connection field in ConnectorComponent

- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/pipeline.proto
- vdp/pipeline/v1beta/pipeline_public_service.proto
Because
- The `watch` endpoints for pipeline releases are not needed.
This commit
- Removes `watch` endpoints for pipeline releases.
> feat(vdp): remove watch endpoints for pipeline releases

- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/pipeline.proto
- vdp/pipeline/v1beta/pipeline_public_service.proto
- vdp/pipeline/v1beta/secret.proto
Because
- We are going to provide a feature that allows users to store secrets under their own namespace or the organization namespaces, the pipeline recipe can reference these secrets.
This commit
- Adds endpoints for secrets management.
- Removes unused `watch` endpoints.
> feat(vdp): add endpoints for secrets management

- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/pipeline.proto
Because
- The `ResponseComponent` is highly coupled with `TriggerByRequest`. We should put them together
This commit
- Merges `ResponseComponent` into `TriggerByRequest` message.
> feat(vdp): remove ResponseComponent and merge it into TriggerByRequest

- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/pipeline.proto
Because
- We will provide functionality that allows users to put secrets in the request to override the owner's secrets.
This commit
- Adds a `secrets` field in trigger endpoints.
> feat(vdp): add `secrets` field in trigger endpoints

- core/mgmt/v1beta/mgmt.proto
- core/mgmt/v1beta/mgmt_private_service.proto
Because
- Though we'll have more metadata in the metrics, it's beneficial to register credit additions / subtractions with a concept, so the DB rows are more meaningful.
This commit
- Adds a `concept` param in the credit subtraction endpoint.
> feat(mgmt): add concept to credit entries

- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/pipeline_public_service.proto
- vdp/pipeline/v1beta/secret.proto
Because
- Originally, we used the `user/secrets` path for managing user secrets. However, this path style is not consistent with the pipeline endpoints. We should change it to `users/<userid>/secrets` for consistency.
This commit
- Adjusts the user secrets endpoint.
> feat(vdp): adjust user secrets endpoint

- core/mgmt/v1beta/mgmt.proto
- openapiv2/core/service.swagger.yaml
- openapiv2/model/service.swagger.yaml
- openapiv2/vdp/service.swagger.yaml
Because
- We need a `Permission` field to indicate whether the user has permission to edit the organization or not.
This commit
- Adds `Permission` field in organization response
> feat(mgmt): add Permission field in organization response

- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/component_definition.proto
Because
- We've merged the `resource_specification` data into `component_specification`.
This commit
- Removes `resource_specification` field in `ConnectorSpec`.
> feat(pipeline): remove resource_specification field in ConnectorSpec

- model/model/v1alpha/model_definition.proto
- openapiv2/model/service.swagger.yaml
Because
- To auto generate the model creation form on console, backend will need to provide spec for model resource
This commit
- add `resource_spec` in `ModelDefinition` message
> chore(model): add resource spec in model definition message

- model/model/v1alpha/model_definition.proto
- openapiv2/model/service.swagger.yaml
Because
- We should combine the spec definition for `model` and `resource`
This commit
- revert the addition of `resource_spec` and add comments
> chore(model): revert addition of resource_spec

- model/model/v1alpha/model.proto
- openapiv2/model/service.swagger.yaml
Because
- We now does not have README to extract `task` when creating model
This commit
- make `task` a required field
> chore(model): make task as required input when creating model

- model/model/v1alpha/model.proto
- openapiv2/model/service.swagger.yaml
Because
- Allow FE to display sample input/output on overview page
This commit
- add sample input/output in model message
> chore(model): add sample input/output in model message

- .github/workflows/add-issue-to-prj.yml
- .github/workflows/add-pr-to-prj.yml
- buf.gen.openapi.yaml
- core/mgmt/v1beta/mgmt_public_service.proto
- core/mgmt/v1beta/openapi.proto.templ
- model/model/v1alpha/model_public_service.proto
- model/model/v1alpha/openapi.proto.templ
- openapiv2/artifact/service.swagger.yaml
- openapiv2/core/service.swagger.yaml
- openapiv2/model/service.swagger.yaml
- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/openapi.proto.templ
- vdp/pipeline/v1beta/pipeline_public_service.proto
Because
- We've unified our Core, VDP, and Model products into a single product, we no longer need to use different endpoint prefixes for them.
- Currently, all endpoints are grouped in the same section, which reduces readability.
This commit
- Removes the `/core`, `/vdp`, and `/model` path prefixes.
- Adds OpenAPI tags for each endpoint.
- Adds `tags` array in `openapi.proto.templ` to control the order of the tags.
> feat(core): remove `/core`, `/vdp`, `/model` path prefix

- model/model/v1alpha/model.proto
- model/model/v1alpha/model_definition.proto
- model/model/v1alpha/model_public_service.proto
- openapiv2/model/service.swagger.yaml
Because
- We need to provide the info about supported regions and hardware for FE to render the model creation page
This commit
- add list available region method
> chore(model): support listing available region for model deployment

- core/mgmt/v1beta/mgmt.proto
- openapiv2/core/service.swagger.yaml
Because
- Credit was updated to reference owners by UID but the endpoint documentation didn't.
This commit
- Replaces references to Credit owner ID by UID.
> fix(vdp): correct reference to credit owner id->uid

- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/common.proto
Because
- We need to have a field to indicate whether the user can release the pipeline or not
This commit
- Returns the `can_release` permission in the pipeline response.
> feat(pipeline): return `can_release` permission in pipeline response

- core/mgmt/v1beta/mgmt.proto
- openapiv2/core/service.swagger.yaml
Because
- We are going to retire the organization freemium plan.
This commit
- Renames organization freemium to non-paid plan.
> feat(mgmt): rename organization freemium to non-paid plan

- core/mgmt/v1beta/mgmt.proto
- openapiv2/core/service.swagger.yaml
Because
- The term `unpaid` is better than `non-paid`.
This commit
- Renames `non-paid` to `unpaid`.
> chore: rename non-paid to unpaid

- core/mgmt/v1beta/mgmt.proto
- openapiv2/core/service.swagger.yaml
Because
- The tier names need to be updated to `free` and `starter`.
This commit
- Updates tier names.
> feat(core): update tier names

- core/mgmt/v1beta/mgmt.proto
- openapiv2/core/service.swagger.yaml
Because
- There was a confusion in the API and database references to the Credit owner.  At the API level we reference the owner by ID, but the database will store the UID reference to be resilient against ID updates.
This commit
- Reverts commit 2b79ef096e60b509c3194a4712bcf8dd58832224 "fix(vdp): correct reference to credit owner id->uid (#321)"
> fix(mgmt): reference owner by ID in credit endpoints.

- core/mgmt/v1beta/mgmt.proto
- core/mgmt/v1beta/mgmt_private_service.proto
- openapiv2/core/service.swagger.yaml
Because
- When checking the remaining credit during execution usage collection, we need round trips to fetch the user ID (user UID->user ID (mgmt)->remaining credit (mgmt)). Moreover, we need to add an authentication layer that shouldn't be needed from a backend service.
This commit
- Adds a private endpoint to fetch the remaining credit.
> feat(vdp): add private remaining credit endpont

- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/pipeline.proto
Because
- we want users to sort the pipeline with a better UX
This commit
- add a params for frontend to sort the pipeline
> feat(vdp): support sorting pipelines options by id and update_time

- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/pipeline.proto
Because
- We should support sorting pipelines under a namespace as well.
This commit
- Supports sorting pipelines under a namespace
> feat(vdp): support sorting pipelines under a namespace

- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/pipeline.proto
Because
- The previous PR put the order_by field in wrong place.
This commit
- Fixes the bug
> chore(vdp): fix sorting pipelines under a namesapce

- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/pipeline.proto
Because
- The description for pipeline ordering is not correct.
This commit
- Updates description for pipeline ordering.
> chore(vdp): update description for pipeline ordering

- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/pipeline.proto
Because
- We are going to introduce `tags` system for pipeline.
This commit
- Adds `tags` field in pipeline.
> feat(pipeline): add `tags` field in pipeline

- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/pipeline.proto
- vdp/pipeline/v1beta/pipeline_public_service.proto
Because:
- We'll provide a helper endpoint that returns metadata that Instill Hub needs.
This commit:
- Adds hub stats endpoints.
> feat(vdp): Add hub stats contract

- vdp/pipeline/v1beta/pipeline.proto
- vdp/pipeline/v1beta/pipeline_public_service.proto
feat(api): stream user pipeline trigger response
Because:
- We want to support streaming responses for triggering user pipelines, which is useful for real-time inference when low latency is a concern.
- The current RPC method for triggering user pipelines returns the response synchronously, which is not suitable for streaming.
> feat(api): stream user pipeline trigger response

- model/model/v1alpha/common.proto
- model/model/v1alpha/model.proto
- openapiv2/model/service.swagger.yaml
- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/pipeline.proto
- vdp/pipeline/v1beta/pipeline_public_service.proto
Because
- Allow FE to determine if a user has the permission to edit or trigger a model
This commit
- add permission object in model message
> chore(model): add permission field in model message

- model/model/v1alpha/model.proto
- openapiv2/model/service.swagger.yaml
Because
- FE needs input and output schema for trigger form rendering
This commit
- add schema fields for model input and output in model message
> chore(model): add schema fields for model input and output

- model/model/v1alpha/model.proto
- model/model/v1alpha/model_public_service.proto
- openapiv2/model/service.swagger.yaml
Because
- Support triggering model without specifying version
This commit
- add endpoint to trigger latest model version
> chore(model): support trigger latest model version

- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/pipeline.proto
- vdp/pipeline/v1beta/pipeline_public_service.proto
Because
- Originally, we used protobuf messages to fully describe the recipe, which is not suitable for our new recipe design. The protobuf `oneof` would introduce an additional nested structure in JSON when using grpc-gateway. This adds extra effort for users when they want to directly write a JSON recipe. We have decided to remove the messages, and the recipe format will now be validated by JSON-schema in the pipeline-backend instead. And in the near future, we'll also change to use YAML recipes, which will be a string and cannot be validated by protobufs anyway.
- We need to provide an endpoint for recipe validation that can return all errors in the recipe.
This commit
- Removes all recipe-related messages and use `structpb` for the recipe instead.
- Updates the response format of …
> feat(vdp): refactor pipeline recipe and optimize the validation endpoint

- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/common.proto
- vdp/pipeline/v1beta/component_definition.proto
- vdp/pipeline/v1beta/pipeline_public_service.proto
Because
- We are going to retire the component categorization of connector and operator and flatten the structure.
- The original `connector-definitions` and `operator-definitions` endpoints will be deprecated.
This commit
- Redesigns the `component-definitions` endpoint, merges the content from the old `connector-definitions` and `operator-definitions` endpoints.
Note
- The [website](https://github.com/instill-ai/instill.tech) will be affected by the endpoint refactor, so we'll update it accordingly.
> feat(vdp): redesign component-definitions endpoint

- artifact/artifact/v1alpha/artifact.proto
- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/pipeline.proto
Because
- We'd like to show some pipeline run statistic data, including `number_of_runs` and `last_run_time`.
This commit
- Returns pipeline run stats.
> feat(vdp): return pipeline run stats

- model/model/v1alpha/model.proto
- model/model/v1alpha/model_public_service.proto
- openapiv2/model/service.swagger.yaml
Because
- Model overview page needs to retrieve input and output data from latest model async trigger
This commit
- add endpoints to get latest operation result
> chore(model): add get latest model operation

- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/pipeline.proto
Because:
The request needs to match TriggerUserPipelineRequest
This commit:
Changes the request payload with the updated data model
> feat(vdp): Update payload for TriggerUserPipelineWithStreamRequest

- artifact/artifact/v1alpha/artifact.proto
- artifact/artifact/v1alpha/artifact_public_service.proto
- openapiv2/artifact/service.swagger.yaml
Because
other backend apps use `id` instead of `uid` to communicate with FE.
This commit
follow the convention
> chore(kb): change parameter name

- .github/workflows/sync-api-docs.yml
- core/mgmt/v1beta/metric.proto
- core/mgmt/v1beta/mgmt_public_service.proto
- openapiv2/core/service.swagger.yaml
Because
- Instill Cloud needs to display the credit consumption of an owner as a chart.
This commit
- Adds the contract for the chart information. In pipeline metrics the total
count is served by a different endpoint. For now, we only want to sum amounts
by time slot so a single endpoint fits our use case.
Rough example of the returned data (without the total sum):
```
Result: _result
Table: keys: [_time]
_time:time                  amount:float
------------------------------  ----------------------------
2024-06-10T18:15:00.000000000Z                         20.85
Table: keys: [_time]
_time:time                  amount:float
------------------------------  ----------------------------
2024-06-10T18:20:00.000000000Z                         20.45
Table: keys: [_time]
_time:time …
```
> feat(mgmt): add credit consumption chart endpoint

- buf.gen.openapi.yaml
- openapiv2/artifact/service.swagger.yaml
- openapiv2/core/service.swagger.yaml
- openapiv2/model/service.swagger.yaml
- openapiv2/vdp/service.swagger.yaml
Because
- Currently, our API HTTP request and response bodies are a mix of camelCase and snake_case, which is not consistent.
This commit
- Uses camelCase for HTTP bodies.
> feat(all): use camelCase in HTTP bodies

- openapiv2/core/service.swagger.yaml
Because
- The last commit, which transformed params to camelCase, didn't take into
account a previous merge.
This commit
- Regenerate OpenAPI to transform credit chart endpoint to camelCase
> fix(docs): regenerate OpenAPI with camelCase

- core/mgmt/v1beta/metric.proto
- model/model/v1alpha/model.proto
- model/model/v1alpha/model_private_service.proto
- openapiv2/model/service.swagger.yaml
Because
- We are missing an endpoint to deploy org models
This commit
- add missing admin org model methods
> chore(model): add missing admin org model methods

- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/pipeline.proto
- vdp/pipeline/v1beta/pipeline_public_service.proto
Because:
- We want to support streaming responses for triggering user pipelines, which is useful for real-time inference when low latency is a concern.
- The current RPC method for triggering user pipelines returns the response synchronously, which is unsuitable for streaming.
> feat(vdp): stream Organization pipeline trigger response

- core/mgmt/v1beta/mgmt.proto
- core/mgmt/v1beta/mgmt_public_service.proto
- openapiv2/core/service.swagger.yaml
Because
- Instill Cloud must allow for credit purchase & purchase history.
This commit
- Exposes the data required in the purchase page via 2 endpoints:
- Get remaining credit returns detailed information about remaining credit.
- List purchases returns a paginated list of credit purchases.
> feat(mgmt): add credit purchase endpoints

- core/mgmt/v1beta/mgmt.proto
- vdp/pipeline/v1beta/pipeline.proto
Because
- The `last_use_time` of `ApiToken` should be optional since it might never be used.
This commit
- Makes `last_use_time` in `ApiToken` optional.
> chore(mgmt): make ApiToken `last_use_time` optional

- artifact/artifact/v1alpha/artifact.proto
- artifact/artifact/v1alpha/artifact_public_service.proto
- model/model/v1alpha/model.proto
- model/model/v1alpha/model_public_service.proto
- openapiv2/model/service.swagger.yaml
- vdp/pipeline/v1beta/pipeline.proto
Because
- id is ambiguous, use `version` instead
This commit
- rename `id` to `version`
> chore(model): rename model version id to version

- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/pipeline.proto
Because
- When users clone a pipeline, we should provide the ability to let them configure the `description` and `sharing` settings during the cloning process.
- We want to track how many times a pipeline has been cloned.
This commit
- Adds `description` and `sharing` fields in the clone endpoints.
- Adds the `number_of_clones` field in the pipeline statistics.
> feat(vdp): add description and sharing fields in pipeline clone endpoints

- core/mgmt/v1beta/mgmt.proto
- core/mgmt/v1beta/mgmt_private_service.proto
- openapiv2/core/service.swagger.yaml
Because
- In pipeline, model, and artifact backends, we might need to verify the namespace type when provided with the namespace UID.
This Commit
- Adds the `CheckNamespaceAdmin` endpoint to `MgmtPrivateService`.
> feat(mgmt): add CheckNamespaceAdmin endpoint

- core/mgmt/v1beta/mgmt.proto
- openapiv2/core/service.swagger.yaml
Because
- Sometimes, the client will want to get the namespace type and namespace UID at the same time.
This commit
- Adds `UID` to the `CheckNamespaceAdminResponse`.
> chore(mgmt): return UID in CheckNamespaceAdminResponse

- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/pipeline.proto
- vdp/pipeline/v1beta/pipeline_public_service.proto
Because
- We will allow users to clone a pipeline from a pipeline release.
This commit
- Adds endpoints for cloning pipeline releases.
> feat(vdp): add endpoints for cloning pipeline release

- artifact/artifact/v1alpha/artifact.proto
- artifact/artifact/v1alpha/artifact_private_service.proto
- openapiv2/artifact/service.swagger.yaml
Because
- model-backend requires method to get detail repo tag
This commit
- add get repo tag
> chore(artifact): add get repo tag endpoint

- common/openapi/v1beta/api_config.conf
- model/model/v1alpha/model_public_service.proto
- openapiv2/model/service.swagger.yaml
- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/pipeline_public_service.proto
Because
- The `Instill-Requester-Uid` header was added to unlock namespace switch in `pipeline-backend`. `model-backend` will also consume it in the model usage handler.
This commit
- Documents the header in the endpoints that use it. There's plenty of duplication but I didn't find a way to extract an option value to a variable, in the proto documentation it states clearly that [option values are literals](https://protobuf.com/docs/language-spec#option-values).
> chore(pipeline): add requester UID header to trigger endpoints

- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/pipeline.proto
Because
- We'd like to allow users to save pipeline profile images and more profile data.
This commit
- Adds `profile_image` and more profile fields.
> feat(vdp): add profile_image and other profile fields

- artifact/artifact/v1alpha/artifact.proto
- artifact/artifact/v1alpha/artifact_public_service.proto
- artifact/artifact/v1alpha/chunk.proto
- openapiv2/artifact/service.swagger.yaml
Because
1. file process has fail status
2. ui need to display chunk info
3. ui need to display chunk highlight
This commit
1. add fail status in file process
2. add chunk related endpoints and its message
3. add source api and its message
> feat(kb): add chunk related api

- artifact/artifact/v1alpha/artifact_public_service.proto
- artifact/artifact/v1alpha/chunk.proto
- openapiv2/artifact/service.swagger.yaml
Because
knowledge base needs to support similar chunk retrieval
This commit
define it in proto
> feat(KB): add similar chunk retrieve api

- artifact/artifact/v1alpha/artifact_public_service.proto
- openapiv2/artifact/service.swagger.yaml
Because
we use namespaces for both users and orgs
This commit
change the owners to namespaces in endpoint
> feat(artifact): namespace endpoint

- model/model/v1alpha/model_public_service.proto
- model/model/v1alpha/openapi.proto.templ
- openapiv2/model/service.swagger.yaml
Because
- VDP and Core APIs group their endpoints by subdomain via tags.
This commit
- Groups Model endpoints in subdomains
- Model
- Model Definition
- Version
- Trigger
- Region
> chore(model): group model endpoints by subdomains

- artifact/artifact/v1alpha/artifact_public_service.proto
- core/mgmt/v1beta/metric.proto
- core/mgmt/v1beta/mgmt_private_service.proto
- core/mgmt/v1beta/mgmt_public_service.proto
- core/usage/v1beta/usage_service.proto
- model/model/v1alpha/model_private_service.proto
- model/model/v1alpha/model_public_service.proto
- openapiv2/core/service.swagger.yaml
- vdp/pipeline/v1beta/pipeline_private_service.proto
- vdp/pipeline/v1beta/pipeline_public_service.proto
Because
- A new dashboard page is going to be implemented, where credit, model and pipeline metrics are displayed.
This commit
- Unifies the shape of the credit and pipeline endpoints in order to reduce the complexity on the client and server.
- Removes unused fields / endpoints.
- The source of truth for the trigger list isn't the metrics endpoint anymore, the logging domain is. The dashboard will redirect to the trigger list powered by the log tables.
- We don't need the success / failure count _per pipeline_ anymore. Instead of a `*TableRecords` endpoint, a new `Count` endpoint is added.
- The `*ChartRecords` endpoints are unified. All the params that are needed in the query (all those that were required or had a default value) are explicit. Though the dashboard won't have a filter …
> feat(mgmt): unify credit and pipeline metric endpoints

- model/model/v1alpha/model_public_service.proto
- openapiv2/model/service.swagger.yaml
- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/pipeline_public_service.proto
Because
- The gRPC `deprecated` tags were not synced to the OpenAPI document
This commit
- Adds `deprecated` tags to the OpenAPI document
> chore(vdp,model): add deprecated tags in OpenAPI

- model/model/v1alpha/model.proto
- model/model/v1alpha/model_public_service.proto
- openapiv2/model/service.swagger.yaml
- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/pipeline.proto
- vdp/pipeline/v1beta/pipeline_public_service.proto
Because
- We should avoid using ambiguous `name` parameter in operation endpoint requests.
This commit
- Uses explicit `operation_id` in operation endpoint requests.
> feat(vdp,model): use explicit operation_id for operation endpoints

- core/mgmt/v1beta/mgmt.proto
- openapiv2/core/service.swagger.yaml
Because
- We no longer charge organizations based on seats.
This commit
- Removes the `max_seats` attribute from the organization subscription.
> chore(mgmt): remove max_seats in organization subscription

- core/mgmt/v1beta/metric.proto
- openapiv2/core/service.swagger.yaml
Because
- `aggregation_window` was copied as a param by accident (trigger count is not aggregated).
This commit
- Removes the parameter from the trigger count request.
> fix(mgmt): remove aggregationWindow from pipeline trigger count request

- model/model/v1alpha/model.proto
- model/model/v1alpha/model_public_service.proto
- openapiv2/model/service.swagger.yaml
- openapiv2/vdp/service.swagger.yaml
Because
- Missing public endpoint for binary file trigger
- Some endpoints are no longer supported in the backend
This commit
- add missing model endpoints for triggering with binary file
- remove unused model endpoints
> chore(model): add missing and retire unused model methods

- model/model/v1alpha/model.proto
Because
- Previous message type is deprecated
This commit
- update latestOperation input and output type
> chore(model): update latestOperation input and output type

- core/mgmt/v1beta/mgmt.proto
- openapiv2/core/service.swagger.yaml
Because
- The Starter plan will be renamed to Pro plan
This commit
- Renames the Starter plan to Pro plan.
> chore(mgmt): rename Starter plan to Pro plan

- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/common.proto
Because
- We need a new component type called `generic`.
This commit
- Adds a new `generic` component type.
> chore(vdp): add new generic component type

- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/component_definition.proto
Because
- We need a new component type called `generic`.
This commit
- Adds a new `generic` type in connector-definitions API.
> chore(vdp): add new generic component type in connector-definitions API

- core/mgmt/v1beta/metric.proto
- core/mgmt/v1beta/mgmt_public_service.proto
- openapiv2/core/service.swagger.yaml
Because
- The new dashboard endpoints introduced breaking changes and the clients won't be ready for the upcoming release.
This commit
- Restores the previous dashboard endpoints
- `ListPipelineTriggerRecords` isn't added back as it had no clients.
> fix(mgmt): restore pipeline dashboard enpoints

- model/model/v1alpha/model.proto
- openapiv2/model/service.swagger.yaml
Because
- GetNamespaceModel should return all its associated version names, to improve the loading speed of Model component.
This commit
- embed version names in model message
> chore(model): embed version names in model message

- vdp/pipeline/v1beta/pipeline.proto
- vdp/pipeline/v1beta/pipeline_public_service.proto
Because
- We are introducing the run-on-event pipeline, which requires endpoints to receive webhook events.
This commit
- Adds run-on-event endpoints.
> feat(vdp): add run-on-event endpoints

- artifact/artifact/v1alpha/chunk.proto
- openapiv2/artifact/service.swagger.yaml
Because
topK is more precise
This commit
change the parameter name
> fix(catalog): update topk to topK

- model/model/v1alpha/model.proto
- model/model/v1alpha/model_public_service.proto
- openapiv2/model/service.swagger.yaml
Because
- model run logging needs to store original task inputs
This commit
- fixed task inputs type
> feat(model): updated model run task input type

- model/model/v1alpha/model_public_service.proto
- openapiv2/model/service.swagger.yaml
- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/pipeline.proto
- vdp/pipeline/v1beta/pipeline_public_service.proto
- **feat(vdp): Add Paginated List of logged Pipeline Runs Endpoint Because:**
- **chore: auto-gen by protobufs**
- **feat(vdp): resolved comments**
Because:
- Users need to retrieve pipeline runs efficiently, either for specific pipelines or across all accessible pipelines.
This commit:
- Returns a paginated list of pipeline runs and components
> feat(vdp): pipeline run logging query APIs

- common/run/v1alpha/run.proto
- model/model/v1alpha/model.proto
- openapiv2/model/service.swagger.yaml
- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/pipeline.proto
Because
- model and pipeline run logging should use same enums
This commit
- added common import for run status & source
> chore(common): added common import for run status & source

- model/model/v1alpha/model.proto
- model/model/v1alpha/model_public_service.proto
- openapiv2/model/service.swagger.yaml
- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/pipeline.proto
Because
- FE supports duration in milliseconds better than protobuf duration type
This commit
- updated total duration type to int in milliseconds
> feat(run): updated total duration type

- artifact/artifact/v1alpha/conversation.proto
- openapiv2/artifact/service.swagger.yaml
Because
list conversations and messages is missing total size in return
This commit
add total_size in return
> fix(catalog): add total size in list api

- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/pipeline.proto
* fixed input & output type
Because
- run logging APIs need to take filter and return raw input&output
This commit
- added query filter and input&output fields in response
> feat(run): pipeline & component run logging query filter

- .github/workflows/sync-api-docs.yml
Because
- The CI didn't update the API version on readme.com.
This commit
- Fixes the bug.
> ci(readme): fix workflow

- model/model/v1alpha/model.proto
- openapiv2/model/service.swagger.yaml
- openapiv2/vdp/service.swagger.yaml
Because
- On the Explore page, all models are publicly available. Displaying the "Run" count will help new users who are unsure of what they need to start with the most popular models. One of the indicators for popularity is the number of times a model has been run.
- For users managing their own resources, it allows a quick understanding of the popularity of their models, whether public or private.
This commit
- add model run count in model message
> feat(model): add model run count

- artifact/artifact/v1alpha/artifact.proto
- artifact/artifact/v1alpha/artifact_public_service.proto
- openapiv2/artifact/service.swagger.yaml
Because
artifact needs to support xlsx type
This commit
support xlsx and make comment clear
> feat(catalog): support xlsx type and rename the api

- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/pipeline.proto
Because
- FE needs data schema for displaying recipe
This commit
- add `data_specification` in pipeline run response
> feat(run): add recipe schema in pipeline run logging

- artifact/artifact/v1alpha/artifact_public_service.proto
- model/model/v1alpha/model.proto
- model/model/v1alpha/model_public_service.proto
- openapiv2/model/service.swagger.yaml
Because
- FE will support triggering model with selected version
This commit
- support getting latest operation with version
> feat(model): support getting latest operation with version

- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/common.proto
- vdp/pipeline/v1beta/integration.proto
- vdp/pipeline/v1beta/openapi.proto.templ
- vdp/pipeline/v1beta/pipeline_public_service.proto
Because
- We want to let users reference a full configuration for pipeline components and include both form (key-value) and OAuth integration methods.
This commit
- Adds the endpoints and entities to manage integrations.
> feat(vdp): add Instill Integration endpoints

- vdp/pipeline/v1beta/integration.proto
Because
- The transpiler needs a unique filter name to implement the fuzzy search on the table columns.
This commit
- Updates the fuzzy search filters on the integration and connection endpoints.
> fix(pipeline): update filter param on integration list endpoints

- .github/workflows/buf-ci.yaml
- .github/workflows/buf-push-gen.yaml
Because
- Buf has created a [consolidated GitHub Action](https://github.com/marketplace/actions/buf-action?_hsenc=p2ANqtz-_Jwa34-K_ZfzESN_DUGsZLrHvGwMrJV4w2FgfaZ7AWLsnBBovUUc2OfH0l5ysnny1vB9KcKf5HqESQGUfnMasV77-pkA&_hsmi=321439226#migrating-from-individual-buf-actions) that runs the individual steps we had scattered across 2 actions.
This commit
- Migrates individual actions to new consolidated Buf action.
> chore(ci): migrate individual buf actions to consolidated action

- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/integration.proto
- vdp/pipeline/v1beta/pipeline_public_service.proto
Because
- Integration endpoints will be served in the next release. Making them public triggers the OpenAPI doc generation.
This commit
- Removes the `INTERNAL` option from the Instill Integration endpoints.
> chore(pipeline): publicize Integration endpoints

- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/integration.proto
Because
- Connections reference integrations by UID internally, so it makes sense to
have that field in the proto object instead of creating an internal
representation. In component definitions, this field is already public.
This commit
- Adds a UID field to the connection object.
> fix(pipeline): add UID to integration object

- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/integration.proto
- vdp/pipeline/v1beta/pipeline_public_service.proto
Because
- Latest design updates imply modifications in the contracts:
- There's no `featured` section in the Integrations list.
- Connection creation dialog contains a help link.
- List of pipelines referencing a connection is paginated.
This commit
- Updates the integration contracts to match the design.
> feat(pipeline): update integration endpoints with design updates

- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/integration.proto
- vdp/pipeline/v1beta/pipeline_public_service.proto
Because
- The path for the connection update had a `{connection.id}` segment, the ID in the request body was overriden by the ID in the path, making the ID impossible to update.
This commit
- Use different parameters for the connection ID (path) and the updated object (body).
- Correct minor documentation issues.
> fix(pipeline): make connection ID mutable

- buf.gen.yaml
Because
- Last PR introduced a change in the Go package name that was intended only for local development.
This commit
- Restores Go package name
> fix(buf): correct go package name

- buf.gen.yaml
Because
- Option was missing from Buf generator, producing an unwanted directory in `protogen-go`
This commit
- Uses `source_relative` option in the validate plugin
> fix(buf): use source_relative option to remove residual generated dir

- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/pipeline.proto
Because
- `PipelineValidationError` is a type generated by the validator package, and an existing type already had that name.
This commit
- Renames `vdp`'s type to `ErrPipelineValidation`.
> fix(buf): rename type conflicting with protoc validator

- artifact/artifact/v1alpha/artifact.proto
- artifact/artifact/v1alpha/artifact_public_service.proto
- openapiv2/artifact/service.swagger.yaml
Because
1. document component is going to support csv and xls
2. Ask & Retrieve API lakcs Instill-Requester-Uid header information
This commit
1. add file type in API spec
2. add Instill-Requester-Uid header info in protobuf
> feat(artifact): support csv file type

- app/app/v1alpha/app_public_service.proto
- app/app/v1alpha/openapi.proto.templ
- artifact/artifact/v1alpha/artifact_public_service.proto
- artifact/artifact/v1alpha/openapi.proto.templ
- model/model/v1alpha/openapi.proto.templ
- openapiv2/app/service.swagger.yaml
- openapiv2/artifact/service.swagger.yaml
- openapiv2/model/service.swagger.yaml
- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/openapi.proto.templ
Because
- Some endpoints reference tags that aren't defined at the root of the OpenAPI
docs.
This commit
- Adds missing tags.
> fix(openapi): add missing tags to OpenAPI definitions

- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/integration.proto
Because
- There was a wrong assumption about integrations, where the setup schema of a connection was different depending on the connection method (key-value or OAuth).
This commit
- Returns a single setup schema per integration.
- Corrects the type of the HelpLink (breaking change, but this field is not used yet).
- Returns the OAuth connection details in the integration.
> feat(vdp): support OAuth configuration on integrations

- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/pipeline.proto
Because
- We need to return the webhook endpoint URLs in the pipeline response so Console can display them to users.
This commit
- Adds the `endpoints` field to the pipeline response.
> feat(vdp): add the `endpoints` field to the pipeline response

- app/app/v1alpha/conversation.proto
- artifact/artifact/v1alpha/artifact_public_service.proto
- openapiv2/app/service.swagger.yaml
- openapiv2/artifact/service.swagger.yaml
Because
list conversations and messages needs to support uid filter
This commit
add conversation and message uid in request
> feat(app): support uid filter in convs and msg list api

- artifact/artifact/v1alpha/artifact.proto
- openapiv2/artifact/service.swagger.yaml
Because
we have to provide the catalog `uid` in list catalog api, frontend can know the corresponging catalog `id`.
This commit
add the uid field
> feat(catalog): add catalog uid in response

- .github/workflows/sync-api-docs.yml
- app/app/v1alpha/app.proto
- app/app/v1alpha/app_public_service.proto
- app/app/v1alpha/openapi.proto.templ
- openapiv2/app/service.swagger.yaml
Because
- App service API will be public and needs to be part of the CI step syncing the OpenAPI files with readme.com
- The old staging version had duplicated Artifact API references and they couldn't be erased from the readme.com UI. A new staging version was created, which contains new IDs
This commit
- Improves App documentation
- Removes unnecessary step in OpenAPI sync CI.
- Updates staging API reference IDs.
- Adds App API reference to the public and private docs at readme.com
> feat(app): upload API reference to readme.com

- artifact/artifact/v1alpha/artifact.proto
- artifact/artifact/v1alpha/artifact_public_service.proto
- openapiv2/artifact/service.swagger.yaml
Because:
- Users need to retrieve catalog runs efficiently, either for specific catalogs or across all accessible catalogs.
This commit:
- Returns a paginated list of catalog runs
> feat(artifact): catalog run logging

- app/app/v1alpha/app.proto
- app/app/v1alpha/app_public_service.proto
- artifact/artifact/v1alpha/chunk.proto
- openapiv2/app/service.swagger.yaml
- openapiv2/artifact/service.swagger.yaml
Because
1.  app will not be bound to only one conversation
2. FE needs to fetch chunks by uid
3. update app comment lack informative
This commit
1. remove the `last_ai_app_conversation_uid`
2. add chunk_uids in list chunk apis
3. add more info in update app request
> feat(catalog): list chunks by uid

- artifact/artifact/v1alpha/artifact_public_service.proto
- artifact/artifact/v1alpha/chunk.proto
- openapiv2/artifact/service.swagger.yaml
Because
- Python SDK artifact_client functions, and the documentation should be consistent to ensure clarity and ease of use.
This commit
- rename SimilarityChunksSearch to ViewChunks
> feat(artifact): rename SimilarityChunksSearch to ViewChunks

- artifact/artifact/v1alpha/artifact_public_service.proto
- artifact/artifact/v1alpha/chunk.proto
- openapiv2/artifact/service.swagger.yaml
Reverts instill-ai/protobufs#473
Because
accidentally there was a misundersatnding regarding the revising document requirement.
This commit 
revert the change.
> fix(artifact): rename ViewChunks to SimilarityChunksSearch 

- app/app/v1alpha/conversation.proto
- openapiv2/app/service.swagger.yaml
Because
- user will need to input top k for retrieving chunks
This commit
- add top k in request
> chore(app): add top k in request

- app/app/v1alpha/conversation.proto
Because
- chat endpoint `top_k` should be optional
This commit
- add optional to top_k
> chore(app): add optional to top_k

- artifact/artifact/v1alpha/chunk.proto
- openapiv2/app/service.swagger.yaml
- openapiv2/artifact/service.swagger.yaml
Because
we'd like to provide as much as possible information about chunk
This commit
add chunk meta data in response
> feat(artifact): add more chunk info in response

- app/app/v1alpha/conversation.proto
- openapiv2/app/service.swagger.yaml
Because
FE needs to restore the last chosen catalog and top K.
This commit
adds the corresponding data in message.
> feat(app): add topk and catalog in conv message

- buf.gen.yaml
- vdp/pipeline/v1beta/integration.proto
Because
- protoc-gen-validate does not fully support as buf plugin for generating python code
This commit
- remove protoc-gen-validate
> fix(buf): remove protoc-gen-validate

- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/pipeline.proto
Because
- We initially used `int64` for `total_size`, but it gets converted to a string when using `grpc-gateway`, which is not ideal.
This commit
- changes the `total_size` type to `int32` to ensure better compatibility with `grpc-gateway` and JSON formatting.
> fix(vdp): the type of `total_size` is wrong

- .pre-commit-config.yaml
- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/pipeline.proto
Because
- The `inputs_reference` and `outputs_reference` data are not accessible to users.
This commit
- removes `inputs_reference` and `outputs_reference` from the `PipelineRun` message.
> chore(vdp): remove inputs_reference and outputs_reference from PipelineRun message

- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/integration.proto
Because
- Example in this filter param contains the old `snake_case` format.
This commit
- Update documentation with a correct example.
> fix(integration): correct integrationId filter documentation

- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/integration.proto
Because
- When a user authorizes an Instill component using OAuth, we want to
display the identity that they used.
This commit
- Add identity field to OAuth connections.
> chore(integration): add identity to OAuth connection

- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/pipeline.proto
- vdp/pipeline/v1beta/pipeline_public_service.proto
Because
- Users should explicitly set the target namespace and pipeline ID when cloning a pipeline.
This commit
- Refactors parameters in the Clone API to support this functionality.
> refactor(vdp): refactor params in Clone API

- model/model/v1alpha/model.proto
- model/model/v1alpha/model_public_service.proto
- openapiv2/model/service.swagger.yaml
- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/pipeline.proto
- vdp/pipeline/v1beta/pipeline_public_service.proto
This pull request is related to https://github.com/instill-ai/protobufs/pull/472 but only includes the ones for run logging data lists, excluding metrics APIs
Because
- the data that users could see on dashboard are different from what they can see on Runs page in a single pipeline or model
This commit
- add new run logging API for dashboard
> feat(run): run logging dashboard list APIs for model and pipeline

- artifact/artifact/v1alpha/artifact_public_service.proto
- artifact/artifact/v1alpha/object.proto
- artifact/artifact/v1alpha/openapi.proto.templ
- openapiv2/artifact/service.swagger.yaml
Because
artifact will support object management on behalf of minIO
This commit
1. provide get upload url API
2. provide get download url API
> feat(artifact): provide object download and upload

- artifact/artifact/v1alpha/artifact.proto
- artifact/artifact/v1alpha/artifact_private_service.proto
- openapiv2/artifact/service.swagger.yaml
Because
blob plugin needs to get the object url information
This commit
adds internal method `GetObjectURL ` in `artifact`
> feat(blob): add internal object url method

- model/model/v1alpha/model.proto
- model/model/v1alpha/model_public_service.proto
- openapiv2/model/service.swagger.yaml
- openapiv2/vdp/service.swagger.yaml
- vdp/pipeline/v1beta/pipeline.proto
- vdp/pipeline/v1beta/pipeline_public_service.proto
Because
- runs pages need to display credit owner field
This commit
- expose requester id in response
- rename rpc name and add documentations (from previous TODOs in https://github.com/instill-ai/protobufs/pull/472)
> feat(run): add requester id in list pipeline/model run response

- core/mgmt/v1beta/metric.proto
- core/mgmt/v1beta/mgmt_public_service.proto
- openapiv2/core/service.swagger.yaml
Because
- Pipeline metrics list endpoint was removed in #387 but it has a client.
This commit
- Reintroduces the endpoint contract. It will be removed with the new
dashboard design.
> fix(metric): reintroduce /metrics/vdp/pipeline/triggers endpoint

- artifact/artifact/v1alpha/artifact.proto
- artifact/artifact/v1alpha/artifact_private_service.proto
- openapiv2/artifact/service.swagger.yaml
Because 
another service needs to get the info of the object stored in the blob, 
Commit 
adds the get object method
> feat(blob): add get object method

- artifact/artifact/v1alpha/artifact.proto
Because
some service may only maintain the object url in their service
This commit
add encode path filed to get back the object url
> feat(blob): add encoded_url_path to retrieve object

- artifact/artifact/v1alpha/artifact.proto
- artifact/artifact/v1alpha/artifact_private_service.proto
- artifact/artifact/v1alpha/object.proto
- openapiv2/artifact/service.swagger.yaml
Because
when API Gateway succeeds in uploading a file, it will update the object info. 
This commit 
adds an internal method for API Gateway to use.
> feat(artifact): provide update object metadata method

- openapi/v2/service.swagger.yaml
- vdp/pipeline/v1beta/integration.proto
Because
- The creation / update requests use an explicit parameter for this info
(instead of the value in the nested object), so this field has become
output-only.
This commit
- Updates the field behaviour of `connection.namespace_id`
> chore(integration): mark connection.namespace_id as output-only

- core/mgmt/v1beta/metric.proto
- core/mgmt/v1beta/mgmt_public_service.proto
- openapi/v2/service.swagger.yaml
Because
- dashboard needs API for model trigger count
This commit
- add new metrics API
> feat(metric): model trigger chart records api

- artifact/artifact/v1alpha/artifact.proto
- artifact/artifact/v1alpha/object.proto
- openapi/v2/service.swagger.yaml
Because:
1. We will support users attaching metadata to uploaded files.
2. The URL should support a non-expiring mode.
This commit:
1. Adds external_metadata in the file message.
2. Allows url_expire to be set to 0, meaning it does not expire.
ref: ins-6685
> feat(blob,catalog): add external_metadata field and correct the comment

- .github/CONTRIBUTING.md
- app/app/v1alpha/app_public_service.proto
- artifact/artifact/v1alpha/artifact_public_service.proto
- core/mgmt/v1beta/mgmt_public_service.proto
- model/model/v1alpha/model_public_service.proto
- openapi/v2/service.swagger.yaml
- vdp/pipeline/v1beta/pipeline_public_service.proto
Because
- This feature was recommended in order to build the C# SDK from the
OpenAPI docs. This will warn SDK users about the stage of the endpoint.
This commit
- Adds extension and documents the convention.
> feat(openapi): add x-stage extension to public endpoints

- artifact/artifact/v1alpha/artifact.proto
- openapi/v2/service.swagger.yaml
Because
- int type usage should align with others
This commit
- change total size type to int32
> fix(run): change total size type to int32

- core/mgmt/v1beta/metric.proto
- core/mgmt/v1beta/mgmt_public_service.proto
Because
- dashboard needs API for model trigger count
This commit
- add new metrics API
> feat(metric): model trigger table records api

- core/mgmt/v1beta/metric.proto
- core/mgmt/v1beta/mgmt_public_service.proto
Because
- dashboard needs API for model trigger completed/error count
This commit
- add new metrics API
> feat(metric): model trigger count api

- core/mgmt/v1beta/mgmt_public_service.proto
- openapi/v2/service.swagger.yaml
Because
- using colons in url paths will cause conflicts either in krakend or gin
This commit
- replace colons with `/`
> fix(metric): fix path conflicts with existing wildcard in gin

- model/model/v1alpha/model.proto
- openapi/v2/service.swagger.yaml
- vdp/pipeline/v1beta/pipeline.proto
Because
- dashboard needs pipeline/model namespace id to redirect
This commit
- add namespace id in response
> fix(run): add namespace id in response

- openapi/v2/service.swagger.yaml
- vdp/pipeline/v1beta/common.proto
- vdp/pipeline/v1beta/component_definition.proto
- vdp/pipeline/v1beta/pipeline_public_service.proto
Because
- We’re introducing the run-on-event pipeline, which requires providing setup and message schemas so users can understand the event message format.
This commit
- Adds event schemas to component definitions.
- Removes deprecated connector and operator definitions API.
> feat(vdp): add event schema in component definitions

- openapi/v2/service.swagger.yaml
- vdp/pipeline/v1beta/component_definition.proto
Because
- We want to include title and description information in the message.
This commit
- Updates the EventSpecification message structure.
> chore(vdp): adjust EventSpecification message

- vdp/pipeline/v1beta/pipeline.proto
- vdp/pipeline/v1beta/pipeline_public_service.proto
Because
- We’re introducing the run-on-event feature. For some applications, we can only register a single webhook URL rather than a unique URL per pipeline. In this case, we need an event router to route and dispatch events to the appropriate pipelines.
This commit
- introduces `DispatchPipelineWebhookEvent` endpoint.
> feat(vdp): introduce `DispatchPipelineWebhookEvent` endpoint

- app/app/v1alpha/conversation.proto
- openapi/v2/service.swagger.yaml
Because
- support choosing LLM model and providing instruction
This commit
- add optional `llm_model` and `user_instructions`
> chore(app): add optional parameters

- core/mgmt/v1beta/metric.proto
- core/mgmt/v1beta/mgmt_public_service.proto
- openapi/v2/service.swagger.yaml
Because
- Pipeline and credit endpoints have different params and schemas.
- Some of the information served by the existing endpoints will be handled by the pipeline run feature.
This commit
- Adds endpoints to serve the new dashboard design:
- `GetPipelineTriggerCount` path is updated to align with API guidelines.
- `ListCreditConsumptionChartRecords` path is updated to align with API guidelines (previous path will be kept in the gateway to keep the current UX running).
- `ListPipelineTriggerChartRecords` is added.
- A separate PR will take care of removing the deprecated endpoints once the new dashboard is rolled out.
> feat(mgmt): update metrics endpoints to serve new dashboard design

- openapi/v2/service.swagger.yaml
- vdp/pipeline/v1beta/integration.proto
Because
- The `schemas` field was added under the wrong assumption that the
integration schemas would differ across connection methods (OAuth vs
key-value).
- After deprecating this field and providing an alternative `setupSchema`
field, all the clients for the deprecated one have been removed.
Therefore, removing the deprecated field won't break any client.
This commit
- Removes the deprecated `schemas` field.
> chore(integration): remove deprecated `schemas` field

- openapi/v2/service.swagger.yaml
- vdp/pipeline/v1beta/integration.proto
- vdp/pipeline/v1beta/pipeline.proto
- vdp/pipeline/v1beta/pipeline_private_service.proto
Because
- When a pipeline recipe references a connection, that connection ID will
be fetched from the requester's namespace.
- This forces requesters to create connections in order to trigger
pipelines from other namesapces.
This commit
- Adds a `connectionReferences` field in the pipeline trigger data, which
allows clients to override the references in the recipe with per-batch
references.
- Adds a private endpoint to fetch connections by UID, needed in the
1-minute to impact project.
> feat(pipeline): allow connection override in trigger data

- vdp/pipeline/v1beta/pipeline_public_service.proto
Because
- The old webhook endpoints are deprecated and no longer in use.
This commit
- Removes the outdated webhook endpoints.
> chore(vdp): remove old webhook endpoints

- vdp/pipeline/v1beta/integration.proto
Because
- `LookUpConnectionAdminRequest` should contain the connection UID, not the namespace ID.
This commit
- Update the object with the right field name.
> fix(connection): correct param in lookup endpoint

- .github/workflows/buf-ci.yaml
- .github/workflows/buf-gen-openapi.yaml
- artifact/artifact/v1alpha/artifact_public_service.proto
- model/model/v1alpha/model.proto
- model/model/v1alpha/model_public_service.proto
- openapi/v2/service.swagger.yaml
- vdp/pipeline/v1beta/pipeline.proto
- vdp/pipeline/v1beta/pipeline_public_service.proto
Because
- The `PipelineRun` and `ModelRun` objects have confusing documentation for
the requester, runner and owner of a pipeline/model run.
This commit
- Recovers changes in #513 improving the object naming and documentation.
> fix(pipeline-run,model-run): clarify actors in Run objects

- app/app/v1alpha/agent.proto
- app/app/v1alpha/conversation.proto
- openapi/v2/service.swagger.yaml
Because
1. FE will set the connection in chat level
2. FE will use breakpoint to continue the chat after setting up the connection
This commit
add this two fields
> feat(agent): support breakpoint and connection

- app/app/v1alpha/agent.proto
- openapi/v2/service.swagger.yaml
Because
tools have description 
This commit
retrun tool description for FE
> fix(agent): add description for tool

- app/app/v1alpha/agent.proto
- app/app/v1alpha/conversation.proto
- openapi/v2/service.swagger.yaml
Because
request and response use the same struct which causes some not necessary fields in reqeust.
This commit
introduce the new message type for request
> chore(agent): refactor the request

- artifact/artifact/v1alpha/artifact.proto
- artifact/artifact/v1alpha/artifact_public_service.proto
- openapi/v2/service.swagger.yaml
Because
in chat ui, user can move file from temporal catalog to persistent one
This commit
add contract
ref: INS-7085
> feat(artifact): add move file method

- model/model/v1alpha/model.proto
- openapi/v2/service.swagger.yaml
Because
- provide display name for each hardware type
This commit
- update hardware message
> chore(model): update hardware message type

- model/model/v1alpha/model.proto
- openapi/v2/service.swagger.yaml
Because
- hardware should stay as string
This commit
- reverts commit 99c515cd3e003401e5ba92abf9a53ce1b21f8ffa.
> chore(model): Revert "chore(model): update model hardware prop type (#536)"

- openapi/v2/service.swagger.yaml
- vdp/pipeline/v1beta/pipeline.proto
Because
- When the blob data associated to a pipeline / component run expires, the backend will stop serving it. It will be useful to both backend and clients to know that the data isn't there because it expired (instead of because an error occurred).
This commit
- Adds a field with the blob data expiration data to the run entities.
> feat(pipeline): add blob expiration time to run logs

- app/app/v1alpha/app_public_service.proto
- app/app/v1alpha/table.proto
- openapi/v2/service.swagger.yaml
Because
- we need to allow users to move rows.
This commit
- adds the move-rows API.
> feat(table): add move-rows API

- app/app/v1alpha/table.proto
- openapi/v2/service.swagger.yaml
Because
- The original default behavior when `afterRowUID` is nil differs between inserting and moving rows.
This commit
- Uses `beforeRowUID` instead of `afterRowUID` when inserting or moving rows.
> chore(table): use beforeRowUID when inserting or moving rows

- app/app/v1alpha/table.proto
- openapi/v2/service.swagger.yaml
Because
- users might want to clear cells with no value.
This commit
- adds support for NullCell in the table.
> chore(table): add NullCell for table

- app/app/v1alpha/table.proto
- openapi/v2/service.swagger.yaml
Because
- we'd like to return the actual order of the rows in the API response.
This commit
- adds an order field for rows, starting from 1.
> chore(table): add order field for row

- app/app/v1alpha/app_public_service.proto
- app/app/v1alpha/table.proto
This commit
- adds num_rows for mock api
> chore(table): add num_rows for mock api

- agent/agent/v1alpha/agent.proto
- agent/agent/v1alpha/agent_public_service.proto
- agent/agent/v1alpha/chat.proto
- agent/agent/v1alpha/table.proto
- openapi/v2/conf.proto
- openapi/v2/service.swagger.yaml
Because
- we need to rename app service to agent service.
This commit
- updates the name.
> feat(agent): rename app-backend to agent-backend

- agent/agent/v1alpha/agent_public_service.proto
- agent/agent/v1alpha/table.proto
- openapi/v2/service.swagger.yaml
Because:
- We need to allow users to export the table in a specified type.
This commit:
- Updates the table export endpoint accordingly.
> chore(table): adjust table export endpoint

- agent/agent/v1alpha/table.proto
- openapi/v2/service.swagger.yaml
This commit
- uses `format` instead of `type` in export API
> chore(table): use `format` instead of `type` in export API

- .github/CONTRIBUTING.md
- README.md
- artifact/artifact/v1alpha/artifact.proto
- buf.md
- core/metric/v1beta/metric.proto
- core/mgmt/v1beta/mgmt_public_service.proto
- core/usage/v1beta/usage.proto
- openapi/v2/conf.proto
- openapi/v2/service.swagger.yaml
- pipeline/pipeline/v1beta/common.proto
- pipeline/pipeline/v1beta/component_definition.proto
- pipeline/pipeline/v1beta/integration.proto
- pipeline/pipeline/v1beta/pipeline.proto
- pipeline/pipeline/v1beta/pipeline_private_service.proto
- pipeline/pipeline/v1beta/pipeline_public_service.proto
- pipeline/pipeline/v1beta/secret.proto
This commit
- renames `vdp` to `pipeline`.
> feat(pipeline): rename VDP to pipeline

- agent/agent/v1alpha/agent_public_service.proto
- agent/agent/v1alpha/table.proto
- openapi/v2/service.swagger.yaml
Because
- We need to store certain agent configurations in tables, columns, or cells.
- We need to enable agents to bind chats with tables.
This commit
- Adds the AgentConfig field to table APIs.
- Adds chat-table binding APIs.
> feat(agent): add the AgentConfig field for table APIs

- artifact/artifact/v1alpha/artifact.proto
- openapi/v2/service.swagger.yaml
Because
- additional summarizing stage is introduced in document parsing
This commit
- add summarizing status
> chore(artifact): add summarizing status

- artifact/artifact/v1alpha/artifact.proto
- artifact/artifact/v1alpha/object.proto
- openapi/v2/service.swagger.yaml
Because
- Instill Artifact file upload does not adopt the latest blob design
This commit
- support blob upload/download for artifact file
> refactor(artifact): support blob upload/download for artifact file

- agent/agent/v1alpha/table.proto
- openapi/v2/service.swagger.yaml
Because
- Some protos need to be redefined for the new design.
This commit:
- Adjusts the table proto and adds enums for column types.
- Removes document, image, audio, and video types.
- Replaces faithfulness check with transparency.
> feat(table): adjust table proto

- agent/agent/v1alpha/agent_public_service.proto
- agent/agent/v1alpha/chat.proto
- openapi/v2/service.swagger.yaml
Because
- support get chat
- support optional catalog id when create chat
This commit
- support get chat
- support optional catalog id when create chat
> chore(chat): support get chat and catalog id when create chat

- agent/agent/v1alpha/chat.proto
- openapi/v2/service.swagger.yaml
Because
- FE needs to render all citations in each round of conversation
This commit
- add citation message type
> chore(agent): add citation message type

- agent/agent/v1alpha/chat.proto
- openapi/v2/service.swagger.yaml
Because
- retrieve file status when sending message
This commit
- add file uids in send message
> chore(chat): add file uids in send message

- agent/agent/v1alpha/table.proto
- openapi/v2/service.swagger.yaml
This commit
- shares the same citation structure between the chat and the table
> chore(agent): share the same citation structure between the chat and the table

- agent/agent/v1alpha/table.proto
- openapi/v2/service.swagger.yaml
This commit
- adjusts file cell format to use file uid instead of file url
> chore(table): adjust file cell format

- agent/agent/v1alpha/chat.proto
- openapi/v2/service.swagger.yaml
Because
- transparency pipeline requires extract method
This commit
- add extract method
> chore(agent): add extract method

- artifact/artifact/v1alpha/artifact_private_service.proto
- artifact/artifact/v1alpha/file_catalog.proto
- openapi/v2/service.swagger.yaml
Because
- Support transparency for deep analysis content
This commit
- add get chat file
> chore(artifact): add get chat file

- artifact/artifact/v1alpha/file_catalog.proto
- openapi/v2/service.swagger.yaml
Because
- use bytes for markdown content
This commit
- use bytes for markdown content
> chore(artifact): use bytes for markdown content

- artifact/artifact/v1alpha/artifact.proto
- artifact/artifact/v1alpha/artifact_public_service.proto
- openapi/v2/service.swagger.yaml
Because
- We need a new endpoint to return file information with summary and download_url
This commit
- adds GetCatalogFile API
- adds summary and download_url for File
> chore(artifact): add GetCatalogFile API

- buf.yaml
- model/model/v1alpha/model.proto
- model/model/v1alpha/model_ray_serve.proto
- model/model/v1alpha/model_ray_user_defined.proto
- openapi/v2/service.swagger.yaml
Because
- We need to support Ray integration for our model service
- Ray uses specific protobuf definitions that need to be incorporated
- Some Ray protobuf files don't follow our standard naming conventions
This commit
- Adds protobuf definitions for Ray model service
- Configures `buf.yaml` to ignore Ray-specific protobuf files
- Enables comment-based lint ignores to handle Ray's non-standard naming conventions
> feat(ray): add protobuf for model and ray

- buf.yaml
- model/ray/serve.proto
Because
- Ray protobuf has the package name `ray.serve`
This commit
- move Ray `serve.proto` under an independent `ray` folder
> fix(model): fix package ray.serve

- buf.gen.openapi.yaml
- buf.gen.yaml
- model/ray/serve.proto
- model/ray/v1alpha/user_defined.proto
- openapi/v2/conf.proto
- openapi/v2/service.swagger.yaml
Because:
- The previous proto files were outdated and didn't match the upstream Ray project
- User-defined services need to be separated for better code organization and maintainability
- Updated plugin versions provide better compatibility and bug fixes
This commit:
- Updates `model/ray/serve.proto` with the latest Ray Serve protocol buffers
- Creates a new `user_defined.proto` file for custom service definitions
- Updates plugin versions in both build configuration files
Note:
- The `buf breaking` CI failure is due to the update of `ray.serve`
> chore(ray): update ray.serve and ray user defined type

- agent/agent/v1alpha/agent_public_service.proto
- agent/agent/v1alpha/table.proto
- openapi/v2/service.swagger.yaml
Because:
- We need to introduce new features — for example, more detailed control over column auto-computation, allowing users to fine-tune cell-level behavior.
- We used the column name as the key for the column definition map and the cell map. This isn’t ideal, since the column name might change.
This commit:
- Optimizes table endpoints.
- Uses column UID as the key of column definition map and the cell map.
> feat(table): optimize table endpoints

- agent/agent/v1alpha/chat.proto
- openapi/v2/service.swagger.yaml
Because
- Currently, the chat API accepts a file UID as input, but this requires the frontend to bind the file to the catalog first. We’d like to simplify this flow so that the frontend doesn’t need to manage the catalog. Therefore, we need to allow users to send the file using an object UID, which doesn’t need to be bound to the catalog.
This commit
- Uses the object UID as input.
> chore(agent): add object UID for chat

- agent/agent/v1alpha/table.proto
- openapi/v2/service.swagger.yaml
Because
- We want to use UIDs as the column identifiers
This commit:
- Uses column UIDs to set the column context
> chore(table): use column uids to set column context

- agent/agent/v1alpha/chat.proto
- openapi/v2/service.swagger.yaml
Because
- We want to allow users to select tables as the context of a chat.
This commit
- Adds context parameters for the chat.
> chore(chat): add context parameters for chat

- agent/agent/v1alpha/table.proto
- openapi/v2/service.swagger.yaml
Because
- The table will support draft mode for constructing the schema without data.
This commit
- Adds the `draft_mode` field to the table message.
> chore(table): add draft_mode field to the table message

- agent/agent/v1alpha/chat.proto
- openapi/v2/service.swagger.yaml
Because
- we need to return message metadata so that users can see it in the chat history.
This commit
- returns metadata for messages.
> chore(chat): return metadata for messages

- agent/agent/v1alpha/chat.proto
- openapi/v2/service.swagger.yaml
Because
- we need to return message metadata so that users can see it in the chat stream
This commit
- returns metadata in chat stream.
> chore(chat): return message metadata in streaming

- agent/agent/v1alpha/chat.proto
- agent/agent/v1alpha/common.proto
- agent/agent/v1alpha/table.proto
- openapi/v2/service.swagger.yaml
Because
- We need to provide column descriptions
- We need to include table created/updated events in the chat stream of the table builder agent
This commit
- Adds a description field in the column definition
- Adds table created/updated events in the chat stream
> chore(table): add description field in column-definition

- agent/agent/v1alpha/table.proto
- openapi/v2/service.swagger.yaml
Because
- We are not using the table ID for any purpose, and it’s not user-friendly, we’ll keep only the UID and title.
This commit
- Removes the table ID.
> chore(table): remove table ID

- agent/agent/v1alpha/table.proto
- openapi/v2/service.swagger.yaml
Because
- users will want to set up the available values for the columns.
this commit
- adds column selection configuration.
> chore(table): add column selection config

- agent/agent/v1alpha/table.proto
- openapi/v2/service.swagger.yaml
Because
- The console needs the full URL path to the file for preview.
This commit
- Returns file_url in the file cell object.
> chore(table): return file_url in file cell object

- model/ray/README.md
- model/ray/v1alpha/user_defined.proto
Because
- prefer stick with default naming as in Ray document
This commit
- rename the custom Ray service
> chore(model,ray): rename user defined service

- agent/agent/v1alpha/table.proto
- openapi/v2/service.swagger.yaml
Because
- The table title can be optional when draft mode is enabled.
This commit
- Makes the table title optional.
> chore(table): make the table title optional

- agent/agent/v1alpha/agent_public_service.proto
- agent/agent/v1alpha/table.proto
- openapi/v2/service.swagger.yaml
Because
- We’d like to provide the table template feature so that users can easily create tables from templates.
This commit
- Adds table template endpoints.
> chore(table): add table template endpoints

- agent/agent/v1alpha/agent_public_service.proto
- agent/agent/v1alpha/table.proto
- openapi/v2/service.swagger.yaml
Because
- We are going to treat the table template as a read-only table instead of a new kind of resource.
This commit
- Refactors the template endpoints
- Adds a permission field to the table
> chore(table): refactor template endpoints

- agent/agent/v1alpha/table.proto
- openapi/v2/service.swagger.yaml
Because
- we'd like to support patch operation for draft_mode field in the table.
This commit
- makes `table.draft_mode` optional
> chore(table): make table.draft_mode optional

- core/mgmt/v1beta/mgmt.proto
- openapi/v2/service.swagger.yaml
This commit
- Renames the `PLAN_PRO` as `PLAN_STARTER` in the `Subscription` type.
> chore(subscription): rename PLAN_PRO as PLAN_STARTER

- agent/agent/v1alpha/folder.proto
- openapi/v2/service.swagger.yaml
Because
- we want to return the file count and total size of the folder catalog in the response.
This commit
- add CatalogInfo into folder response.
> chore(agent): add Catalog Info into folder response

- artifact/artifact/v1alpha/artifact.proto
- openapi/v2/service.swagger.yaml
Because
- Some catalogs require a custom document conversion pipeline.
This commit
- Adds a parameter in the catalog creation request to specify the
conversion pipelines associated to it.
> feat(catalog): specify document conversion pipelines in catalog creation

- artifact/artifact/v1alpha/artifact.proto
- openapi/v2/service.swagger.yaml
This commit
- Corrects the syntax in the `converting_pipelines` documentation:
- `doc*` created an unwanted emphasis.
- The code blocks produce one tab per block and accept a language and
a tab title.
> fix(catalog): correct converting_pipelines param documentation

- agent/agent/v1alpha/common.proto
- openapi/v2/service.swagger.yaml
Because
- We’re no longer relying on the catalog for files uploaded in chat, so we need to provide more file details directly in the message response.
This commit
- Updates the ChatAttachments object.
> chore(chat): update the ChatAttachments object

- agent/agent/v1alpha/agent_public_service.proto
- agent/agent/v1alpha/table.proto
- openapi/v2/service.swagger.yaml
Because
- we need to allow users to enhance the column instructions based on the current settings
This commit
- adds the EnhanceColumnDefinitionInstructions API
> chore(table): add EnhanceColumnDefinitionInstructions API

- .github/workflows/sync-api-docs.yml
- agent/agent/v1alpha/table.proto
- openapi/v2/service.swagger.yaml
This commit
- replaces free-form color values with a predefined color enum for selection
> chore(table): replace free-form color values with a predefined color enum for selection

- agent/agent/v1alpha/common.proto
- openapi/v2/service.swagger.yaml
This commit
- change catalog context from using `id` to `uid`
> chore(chat): change catalog context

- .github/workflows/sync-api-docs.yml
Because
- PR should trigger the OpenAPI docs update workflow only when the OpenAPI docs have changes
This commit
- fixes the logic
> chore(workflows): add PR path conditoin for api doc update

- artifact/artifact/v1alpha/artifact.proto
- artifact/artifact/v1alpha/artifact_private_service.proto
- artifact/artifact/v1alpha/artifact_public_service.proto
- artifact/artifact/v1alpha/chunk.proto
- artifact/artifact/v1alpha/file_catalog.proto
- openapi/v2/service.swagger.yaml
Because
- Catalog files shouldn't be identified by their filename but by their UID.
This commit
- Removes the file ID param as a file identifier from the API.
- Refactors / polishes the API to align with other services.
- Some of these changes introduce new fields with better names /
definitions but don't delete the previous ones for backwards
compatibility. When the clients have been updated, the fields will be
removed.
> chore(artifact): remove filename uniqueness

- core/mgmt/v1beta/mgmt.proto
- core/mgmt/v1beta/mgmt_private_service.proto
- core/mgmt/v1beta/mgmt_public_service.proto
- openapi/v2/service.swagger.yaml
Because
- Instead of having a `PLAN_FREE` subscription (which exists only in the
backend, not on Stripe), we're going to offer a free trial for the
starter and team plans.
This commit
- Updates the subscription object and methods to reflect this change,
deprecating the free plan enums and documenting the plan and status
enums.
> feat(subscription): update documentation and entities for user/org subscription

- core/mgmt/v1beta/mgmt.proto
- core/mgmt/v1beta/mgmt_public_service.proto
- openapi/v2/service.swagger.yaml
Because
- We want to allow users to invite others to become organization members via email.
This commit
- Adds invite-members endpoints.
> chore(mgmt): add invite-members endpoints

- core/mgmt/v1beta/mgmt.proto
- openapi/v2/service.swagger.yaml
Because
- We need to determine whether users are eligible to create an organization under the trial plan.
This commit
- Adds a field to indicate whether a user is eligible for an organization trial.
> chore(mgmt): add a field to indicate whether the user is eligible for org trial

- LICENSE
- buf.yaml
- openapi/v2/conf.proto
- openapi/v2/service.swagger.yaml
Because
- OpenAPI protobuf is for only configuration for the auto-gen logic
This commit
- removes OpenAPI protobuf exposing to BSR
> chore(openapi): remove protobuf exposing to BSR

- buf.md
Because
- BSR README is outdated
This commit
- updates `buf.md`
> docs(buf): update README

- artifact/artifact/v1alpha/artifact.proto
- openapi/v2/service.swagger.yaml
This commit
- Documents the indexing (1-based) in chunk references for paged
documents.
> chore(catalog): specify 1-based index for page citation
